import { RandomGoods, TradeTextType } from "~/features/products/product";

export const _4thAnniversarySTELLA_缶バッジ: RandomGoods = {
  id: "缶バッジ「STELLA」",
  slug: "キラキラ缶バッジ「STELLA」",
  name: "キラキラ缶バッジ「STELLA」",
  year: 2026,
  series: "4th Anniversary",
  category: "缶バッジ",
  tradeText: TradeTextType.NameOnly,
  url: "/takaneko/goods/2026/2026-08-06_缶バッジ「STELLA」.webp",
  width: 222,
  height: 224,
  variants: [
    { id: 1, name: "城月菜央", description: "" },
    { id: 2, name: "涼海すう", description: "" },
    { id: 3, name: "橋本桃呼", description: "" },
    { id: 4, name: "葉月紗蘭", description: "" },
    { id: 5, name: "東山恵里沙", description: "" },
    { id: 6, name: "日向端ひな", description: "" },
    { id: 7, name: "星谷美来", description: "" },
    { id: 8, name: "松本ももな", description: "" },
    { id: 9, name: "籾山ひめり", description: "" },
  ],
  withFrame: true,
  positions: [
    { id: 1, x: 3, y: 3, width: 70, height: 70 },
    { id: 2, x: 76, y: 3, width: 70, height: 70 },
    { id: 3, x: 149, y: 3, width: 70, height: 70 },
    { id: 4, x: 3, y: 76, width: 70, height: 70 },
    { id: 5, x: 76, y: 76, width: 70, height: 70 },
    { id: 6, x: 149, y: 76, width: 70, height: 70 },
    { id: 7, x: 3, y: 150, width: 70, height: 70 },
    { id: 8, x: 76, y: 150, width: 70, height: 70 },
    { id: 9, x: 149, y: 150, width: 70, height: 70 },
  ],
};
