import { MediaDetails } from "~/features/media/types";

export const metadata2024: MediaDetails[] = [
  {
    kind: "youtube",
    key: "69Kukwgz8R0",
    title: "【抜き打ち】たくさんのモデルたちに年内最後の体重測定!!【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-12-28",
    mediaUrl: "https://youtu.be/69Kukwgz8R0",
    imageUrl: "https://i.ytimg.com/vi/69Kukwgz8R0/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://abema.tv/video/episode/88-77_s1_p293",
    title:
      "#258:【ラパルフェ】「モノマネをやめたい」M-1準々決勝のネタが物議を醸した2人が真剣悩み相談!!【完全版】 - しくじり先生 俺みたいになるな!! - 本編 (バラエティ) | 無料動画・見逃し配信を見るなら | ABEMA",
    authorName: "ABEMA",
    publishedAt: "2024-12-28",
    mediaUrl: "https://abema.tv/video/episode/88-77_s1_p293",
    imageUrl:
      "https://image.p-c2-x.abema-tv.com/image/programs/88-77_s1_p293/thumb002.png?height=720&quality=75&version=1755068737&width=1280",
    category: "video",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    key: "bCM_vq0rScs",
    title:
      "【ムチャぶり】抜群の表現力＆歌唱力をもつモデルを発見！今からここでカラオケしてください!!【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-12-22",
    mediaUrl: "https://youtu.be/bCM_vq0rScs",
    imageUrl: "https://i.ytimg.com/vi/bCM_vq0rScs/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://strmweb.jp/?p=15750",
    title:
      "高嶺のなでしこ「この10人だからこそ出せる色がある。これからも1人1人が個性を出せるようなグループを作り続けたい」INTERVIEW",
    authorName: "STREAM（ストリーム）",
    publishedAt: "2024-12-13",
    mediaUrl: "https://strmweb.jp/?p=15750",
    imageUrl: "https://strmweb.jp/home/wp-content/uploads/2024/12/A7S00074.jpg",
    category: "article",
    presents: ["城月菜央", "東山恵里沙", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.radionikkei.jp/toraken/42_takakneko.html",
    title:
      "第42回ゲスト研究員は、引き続き高嶺のなでしこの松本ももなさんと籾山ひめりさん！｜虎ノ門 トレンド経済研究所｜エンタメ・カルチャー｜ラジオNIKKEI",
    authorName: "ラジオNIKKEI",
    publishedAt: "2024-12-11",
    mediaUrl: "https://www.radionikkei.jp/toraken/42_takakneko.html",
    imageUrl:
      "https://www.radionikkei.jp/toraken/images/eef2ba81cfc1754d3af102957796c4f0a9969bad.jpg",
    category: "audio",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.walkerplus.com/article/1229695/",
    title: "高嶺のなでしこが2ndシングルを発売！メンバー10名にインタビュー(1/4)｜ウォーカープラス",
    authorName: "ウォーカープラス（Walkerplus）",
    publishedAt: "2024-12-11",
    mediaUrl: "https://www.walkerplus.com/article/1229695/",
    imageUrl: "https://news.walkerplus.com/article/1229695/13783978_615.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://recochoku.jp/ch/recolog/takanenonadeshiko/",
    title:
      "高嶺のなでしこ（城月菜央・松本ももな・籾山ひめり）が2ndシングルで描いた新境地を語る「ずっとそばにいてくださると嬉しいです」",
    authorName: "レコログ",
    publishedAt: "2024-12-11",
    mediaUrl: "https://recochoku.jp/ch/recolog/takanenonadeshiko/",
    imageUrl: "https://recochoku.jp/ch/recolog/wp-content/uploads/2024/12/THP_0042-700x467.jpg",
    category: "article",
    presents: ["城月菜央", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popnroll.tv/articles/41644",
    title:
      "🍭 高嶺のなでしこ［インタビュー］2ndシングルが照らす希望の光、広がるその先の景色「5曲でいろんな一面が見られるので、フルで楽しんでほしい」 - Pop'n'Roll(ポップンロール)",
    authorName: "Pop'n'Roll",
    publishedAt: "2024-12-11",
    mediaUrl: "https://popnroll.tv/articles/41644",
    imageUrl:
      "https://img.popnroll.tv/uploads/news_item/og_image/41644/large__Q8A0806%E3%81%AE%E3%82%B3%E3%83%92%E3%82%9A%E3%83%BC.jpg",
    category: "article",
    presents: ["東山恵里沙", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.oricon.co.jp/news/2358400/",
    title:
      "【インタビュー】高嶺のなでしこ“らしさ”とは？ メンバーが語るグループの方向性とそれぞれの個性 ",
    authorName: "ORICON NEWS",
    publishedAt: "2024-12-11",
    mediaUrl: "https://www.oricon.co.jp/news/2358400/",
    imageUrl:
      "https://contents.oricon.co.jp/upimg/news/2359000/2358400/20241210_131044_p_o_52657688.jpg",
    category: "article",
    presents: ["橋本桃呼", "東山恵里沙", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.vanitymix.jp/music/takanenonadeshiko-4/",
    title: "高嶺のなでしこ VANITYMIX WEB LIMITED INTERVIEW",
    authorName: "VANITYMIX マガジン",
    publishedAt: "2024-12-11",
    mediaUrl: "https://www.vanitymix.jp/music/takanenonadeshiko-4/",
    imageUrl:
      "https://www.vanitymix.jp/wp-content/uploads/2024/12/78a96fd280e3f24fe6e4bfb74d254906-scaled-e1733453120661.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "rIANtpllshE",
    title:
      "高嶺のなでしこ、リレーインタビューでわちゃわちゃ！？新曲「I’M YOUR IDOL / アドレナリンゲーム」徹底解剖&“過去最大規模”ワンマンライブに意気込み【単独インタビュー】",
    authorName: "oricon",
    publishedAt: "2024-12-08",
    mediaUrl: "https://youtu.be/rIANtpllshE",
    imageUrl: "https://i.ytimg.com/vi/rIANtpllshE/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.oricon.co.jp/news/2357995/",
    title:
      "高嶺のなでしこ、グループ結成から2年の現在地語る「家族みたいな存在」　新曲リリース&“過去最大規模”ワンマンに意気込み ",
    authorName: "ORICON NEWS",
    publishedAt: "2024-12-08",
    mediaUrl: "https://www.oricon.co.jp/news/2357995/",
    imageUrl:
      "https://contents.oricon.co.jp/upimg/news/2358000/2357995/20241208_110101_o_90679108.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "static",
    key: "https://outofmusic.net/?p=1286",
    title:
      "【先行掲載・WEBオリジナル記事】＜高嶺のなでしこ＞国立代々木第二体育館公演、開催！ 話題の10人組アイドルグループ、高嶺のなでしこ。注目の2nd Single「Iʼ M YOUR IDOL / アドレナリンゲーム」、総1万6,000字 ロング・インタビュー 前編、先行掲載！。",
    authorName: "OUT of MUSIC",
    publishedAt: "2024-12-07",
    mediaUrl: "https://outofmusic.net/?p=1286",
    imageUrl: "/media/2024/2024-12-07_OUT of MUSIC.webp",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.radionikkei.jp/toraken/41nadeshiko.html",
    title:
      "第41回ゲスト研究員は高嶺のなでしこの松本ももなさんと籾山ひめりさん！｜虎ノ門 トレンド経済研究所｜エンタメ・カルチャー｜ラジオNIKKEI",
    authorName: "ラジオNIKKEI",
    publishedAt: "2024-12-04",
    mediaUrl: "https://www.radionikkei.jp/toraken/41nadeshiko.html",
    imageUrl:
      "https://www.radionikkei.jp/toraken/images/eef2ba81cfc1754d3af102957796c4f0a9969bad.jpg",
    category: "audio",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://cmnow.jp/next/24110522772/",
    title:
      "高嶺のなでしこから橋本桃呼、春野莉々、涼海すうが登場！ 『Iʼ M YOUR IDOL / アドレナリンゲーム』を語る。 – CMNOW WEB",
    authorName: "CMNOW WEB",
    publishedAt: "2024-11-27",
    mediaUrl: "https://cmnow.jp/next/24110522772/",
    imageUrl: "https://cmnow.jp/wp-content/uploads/2024/11/L1100477.jpg",
    category: "article",
    presents: ["涼海すう", "橋本桃呼", "春野莉々"],
  },
  {
    kind: "youtube",
    key: "oTSf8zfMoAY",
    title:
      "【Part.4】ついに最終決戦！この一戦で優勝者が決まる!? 超十代大運動会2024 最終戦 チーム合同リレー（超十代）",
    authorName: "超十代チャンネル【ULTRA TEENS Channel】",
    publishedAt: "2024-11-12",
    mediaUrl: "https://youtu.be/oTSf8zfMoAY",
    imageUrl: "https://i.ytimg.com/vi/oTSf8zfMoAY/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "日向端ひな", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "sm1Y8fQ0fqU",
    title:
      "【Part.3】決勝戦目前。。。勝利の椅子に座るのは私だ!!!総勢36名で行う超椅子取りゲーム！超十代大運動会2024 第3回戦椅子取りゲーム（超十代）",
    authorName: "超十代チャンネル【ULTRA TEENS Channel】",
    publishedAt: "2024-11-11",
    mediaUrl: "https://youtu.be/sm1Y8fQ0fqU",
    imageUrl: "https://i.ytimg.com/vi/sm1Y8fQ0fqU/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "日向端ひな", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "YALM6PgE1sQ",
    title:
      "【Part.2】仲良しは今日で終わりだ。親友達でも手は抜かない！勝つのは私だ！超十代大運動会2024 第2回戦 綱取り！（超十代）",
    authorName: "超十代チャンネル【ULTRA TEENS Channel】",
    publishedAt: "2024-11-10",
    mediaUrl: "https://youtu.be/YALM6PgE1sQ",
    imageUrl: "https://i.ytimg.com/vi/YALM6PgE1sQ/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "日向端ひな", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "EpBnreI1nQY",
    title:
      "【Part.1】超十代チャンネル史上最大級の戦いがついに開幕！超十代大運動会2024 みんなも推しを応援してね!!!（超十代）",
    authorName: "超十代チャンネル【ULTRA TEENS Channel】",
    publishedAt: "2024-11-09",
    mediaUrl: "https://youtu.be/EpBnreI1nQY",
    imageUrl: "https://i.ytimg.com/vi/EpBnreI1nQY/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "日向端ひな", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "CS0BTp4e1IA",
    title: "【重要】超十代チャンネルから皆様に大事なお知らせがあります",
    authorName: "超十代チャンネル【ULTRA TEENS Channel】",
    publishedAt: "2024-11-03",
    mediaUrl: "https://youtu.be/CS0BTp4e1IA",
    imageUrl: "https://i.ytimg.com/vi/CS0BTp4e1IA/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://www.shinmai.co.jp/news/article/CNTS2024102000780",
    title:
      "皆さん、詐欺には気を付けて　「高嶺のなでしこ」春野さん、故郷の駒ヶ根市で一日警察署長を務め啓発｜信濃毎日新聞デジタル　信州・長野県のニュースサイト",
    authorName: "信濃毎日新聞デジタル",
    publishedAt: "2024-10-21",
    mediaUrl: "https://www.shinmai.co.jp/news/article/CNTS2024102000780",
    imageUrl: "https://image.shinmai.co.jp/web-image/20241020/CNTS2024102000390_M.jpg",
    category: "article",
    presents: ["春野莉々"],
  },
  {
    kind: "ogp",
    key: "https://abema.tv/video/episode/88-77_s1_p281",
    title:
      "#248:【臓器売買】筋トレし過ぎで私生活しくじり倒す!!恋人にも振られ借金地獄!?筋肉生活の弊害とは?!【横川尚隆】後編 - しくじり先生 俺みたいになるな!! - 本編 (バラエティ) | 無料動画・見逃し配信を見るなら | ABEMA",
    authorName: "ABEMA",
    publishedAt: "2024-10-18",
    mediaUrl: "https://abema.tv/video/episode/88-77_s1_p281",
    imageUrl:
      "https://image.p-c2-x.abema-tv.com/image/programs/88-77_s1_p281/thumb002.png?height=720&quality=75&version=1755068736&width=1280",
    category: "video",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "MjnzhkdtezY",
    title: "高嶺のなでしこ　2nd ファンミーティング 「酪農応援プロジェクト」コラボメイキング映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2024-10-16",
    mediaUrl: "https://youtu.be/MjnzhkdtezY",
    imageUrl: "https://i.ytimg.com/vi/MjnzhkdtezY/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://natalie.mu/music/pp/churaku-takaneko",
    title:
      "“酪農応援アンバサダー”高嶺のなでしこ、楽しく学びながら発信する酪農家の思いや牛乳の魅力 - 音楽ナタリー 特集・インタビュー",
    authorName: "音楽ナタリー",
    publishedAt: "2024-10-16",
    mediaUrl: "https://natalie.mu/music/pp/churaku-takaneko",
    imageUrl:
      "https://ogre.natalie.mu/media/pp/churaku-takaneko/churaku-takaneko_33859.jpg?imwidth=1280&imdensity=1",
    category: "article",
    presents: ["橋本桃呼", "春野莉々", "東山恵里沙", "星谷美来"],
  },
  {
    kind: "ogp",
    key: "https://abema.tv/video/episode/88-77_s1_p280",
    title:
      "#247:【横川尚隆】筋トレで借金600万!!筋トレ沼にハマりすぎた先に待つ地獄とは!?【ボディビルダー界のレジェンド】 - しくじり先生 俺みたいになるな!! - 本編 (バラエティ) | 無料動画・見逃し配信を見るなら | ABEMA",
    authorName: "ABEMA",
    publishedAt: "2024-10-11",
    mediaUrl: "https://abema.tv/video/episode/88-77_s1_p280",
    imageUrl:
      "https://image.p-c2-x.abema-tv.com/image/programs/88-77_s1_p280/thumb002.png?height=720&quality=75&version=1755068736&width=1280",
    category: "video",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "QdegLqwOZ9E",
    title: "【衝撃】高校生のスクバの中はこんなことになってた...【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-09-28",
    mediaUrl: "https://youtu.be/QdegLqwOZ9E",
    imageUrl: "https://i.ytimg.com/vi/QdegLqwOZ9E/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "Xy8rDxy6Hgs",
    title: "【大失恋】モデルが公開告白！しかし厳しい現実が。。。【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-09-23",
    mediaUrl: "https://youtu.be/Xy8rDxy6Hgs",
    imageUrl: "https://i.ytimg.com/vi/Xy8rDxy6Hgs/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/autumn_uniformsnap/",
    title: "ちょっぴり秋っぽな最新制服SNAP!!",
    authorName: "Popteen Media",
    publishedAt: "2024-09-15",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/autumn_uniformsnap/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/09/85e5417673b5ed4fb94b58d6116e98df-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/charactergoods_present/",
    title: "JKに人気のキャラグッズを大量プレゼントちゃーん♡",
    authorName: "Popteen Media",
    publishedAt: "2024-09-09",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/charactergoods_present/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/08/26057a96dd03d74344b0abec6e090729-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/bachikawafes_part2/",
    title: "Popteenばちかわフェスイベント完全レポート!!PART2",
    authorName: "Popteen Media",
    publishedAt: "2024-09-09",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/bachikawafes_part2/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/08/b2ccab39bc8d1e73a30784e727c2e7f1-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/bachikawafes_part1/",
    title: "Popteenばちかわフェスイベント完全レポート!!PART1",
    authorName: "Popteen Media",
    publishedAt: "2024-09-09",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/bachikawafes_part1/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/08/57fdc87c0fd6fd54911fa4b35ae3e2c2-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "eSb_h9ohh6Q",
    title:
      "【ハプニング】現役アイドル松本ももなの保育士1日体験に密着【高嶺のなでしこ】【HoneyWorks】",
    authorName: "保育士バンク！チャンネル【公式】",
    publishedAt: "2024-09-06",
    mediaUrl: "https://youtu.be/eSb_h9ohh6Q",
    imageUrl: "https://i.ytimg.com/vi/eSb_h9ohh6Q/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな"],
  },
  {
    kind: "youtube",
    key: "spYkHfWCyd8",
    title:
      "【高嶺のなでしこ】2周年記念 Zepp TOUR 2024 「瞬きさえ忘れる。」9/26(木) Zepp Nagoyaにて開催！ティザー映像到着！",
    authorName: "SUNDAY FOLK PROMOTION",
    publishedAt: "2024-08-31",
    mediaUrl: "https://youtu.be/spYkHfWCyd8",
    imageUrl: "https://i.ytimg.com/vi/spYkHfWCyd8/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "BlutW1YWek8",
    title: "【激おこ案件】カメラマンがモデルに怒られました、、、!?【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-08-31",
    mediaUrl: "https://youtu.be/BlutW1YWek8",
    imageUrl: "https://i.ytimg.com/vi/BlutW1YWek8/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "jmGEMZg45xc",
    title:
      "【1曲で２０役超！】ななみなな・カトリーナ陽子・だしおさん・みはるがバズり曲「Bling-Bang-Bang-Born」でモノマネ七変化！！  #まいにち賞レース #つめ込みモノマネGP",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2024-08-30",
    mediaUrl: "https://youtu.be/jmGEMZg45xc",
    imageUrl: "https://i.ytimg.com/vi/jmGEMZg45xc/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "s1ebJP17-TU",
    title: "【涙腺崩壊】さくてぃん感動の卒業ステージ!!モデル全員大泣き状態!?【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-08-25",
    mediaUrl: "https://youtu.be/s1ebJP17-TU",
    imageUrl: "https://i.ytimg.com/vi/s1ebJP17-TU/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "static",
    key: "https://outofmusic.net/?p=599",
    title:
      "【特集ハイライト】＜高嶺のなでしこ＞10人組アイドルグループ 高嶺のなでしこ Digital Single『モテチェン！』インタビュー OUT of MUSIC 86掲載",
    authorName: "OUT of MUSIC",
    publishedAt: "2024-08-20",
    mediaUrl: "https://outofmusic.net/?p=599",
    imageUrl: "/media/2024/2024-08-20_OUT of MUSIC.webp",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "5Ts_rVheplA",
    title:
      "【真夏のアイドルLIVE】FRUITS ZIPPER・高嶺のなでしこ・わーすた ・虹のコンキスタドール・JamsCollection・テラス×テラス～人気アイドルが六本木の夜を熱く盛り上げる!",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2024-08-15",
    mediaUrl: "https://youtu.be/5Ts_rVheplA",
    imageUrl: "https://i.ytimg.com/vi/5Ts_rVheplA/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "B_pTpzsaObE",
    title: "【LuckyFes'24】高嶺のなでしこインタビュー",
    authorName: "LuckyFes",
    publishedAt: "2024-08-04",
    mediaUrl: "https://youtu.be/B_pTpzsaObE",
    imageUrl: "https://i.ytimg.com/vi/B_pTpzsaObE/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_9_hyoushi/summer_nailcatalog/",
    title: "モデルが考えた夏ネイルカタログ♡",
    authorName: "Popteen Media",
    publishedAt: "2024-08-01",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_9_hyoushi/summer_nailcatalog/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/08/e6320525f0ebcabdfb5e6943c53204ea-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_9_hyoushi/best_cosme/",
    title: "Popteenのモデルが選ぶ2024年上半期ベスコスリスト♡",
    authorName: "Popteen Media",
    publishedAt: "2024-08-01",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_9_hyoushi/best_cosme/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/07/0731_cosme-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://ciao.shogakukan.co.jp/topics/157830/",
    title:
      "【高嶺のなでしこ】城月菜央ちゃんに『ショコラの魔法』の魅力を聞いたよ！みづほ梨乃先生の描きおろしイラストも！！ - ちゃおプラス",
    authorName: "ちゃおプラス",
    publishedAt: "2024-07-31",
    mediaUrl: "https://ciao.shogakukan.co.jp/topics/157830/",
    imageUrl:
      "https://cdn.ciao.shogakukan.co.jp/wp-content/uploads/2024/07/a45118ad351d1735a0d1a0274ce66ea5.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://www.idol-culture.jp/geinou/132652/",
    title:
      "“高嶺のなでしこ”籾山ひめり「頼られると頑張りたい」キャプテン就任への思いを告白｜BUBKA Web（ブブカ ウェブ）",
    authorName: "BUBKA Web（ブブカ ウェブ）",
    publishedAt: "2024-07-28",
    mediaUrl: "https://www.idol-culture.jp/geinou/132652/",
    imageUrl: "https://www.idol-culture.jp/wp-content/uploads/2024/07/58_IC.jpg",
    category: "article",
    presents: ["籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.idol-culture.jp/geinou/132651/",
    title:
      "高嶺のなでしこ・籾山ひめり、新曲のお気に入りポイントを明かす「“私も可愛くなれるんだぞ！”っていうメッセージが込められている」｜BUBKA Web（ブブカ ウェブ）",
    authorName: "BUBKA Web（ブブカ ウェブ）",
    publishedAt: "2024-07-27",
    mediaUrl: "https://www.idol-culture.jp/geinou/132651/",
    imageUrl: "https://www.idol-culture.jp/wp-content/uploads/2024/07/15_IC.jpg",
    category: "article",
    presents: ["籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "8sm8FpP8gQ8",
    title:
      "【歌うまアイドルは誰？】高嶺のなでしこ・Peel the Apple・マジカル・パンチライン・LinQの歌姫がかわいさ・ハモリ・表現力で歌唱対決！バズソング「全方向美少女」を熱唱！ #まいにち賞レース",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2024-07-26",
    mediaUrl: "https://youtu.be/8sm8FpP8gQ8",
    imageUrl: "https://i.ytimg.com/vi/8sm8FpP8gQ8/hqdefault.jpg",
    category: "youtube",
    presents: ["東山恵里沙"],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://asageimuse.com/excerpt/23627",
    title: "高嶺のなでしこインタビュー、新曲『モテチェン！』は「勇気を出す手助けができる曲」",
    authorName: "asageiMUSE",
    publishedAt: "2024-07-26",
    mediaUrl: "https://asageimuse.com/excerpt/23627",
    imageUrl:
      "https://asageimuse.com/wp-content/uploads/2024/07/fef3c2d586572ed1b6474b257da9208c.jpg",
    category: "article",
    presents: [],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://nicola.jp/?p=22017",
    title:
      "【高嶺のなでしこ】最新曲『モテチェン！』インタビュー！ たかねこメンバーの「かわいいのための努力」とは？｜TOPICS｜ニコラネット｜nicola公式サイト（新潮社）",
    authorName: "ニコラネット｜nicola公式サイト（新潮社）",
    publishedAt: "2024-07-23",
    mediaUrl: "https://nicola.jp/?p=22017",
    imageUrl: "https://nicola.jp/wp-content/uploads/2024/07/f116246827f34ec7becea912ac8a2af1.png",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.vanitymix.jp/music/takanenonadeshiko-3/",
    title: "高嶺のなでしこ VANITYMIX WEB LIMITED INTERVIEW",
    authorName: "VANITYMIX マガジン",
    publishedAt: "2024-07-19",
    mediaUrl: "https://www.vanitymix.jp/music/takanenonadeshiko-3/",
    imageUrl:
      "https://www.vanitymix.jp/wp-content/uploads/2024/07/018e2b6e8aa4f21b44f838cfd19db6c2-scaled-e1721354632959.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://cmnow.jp/entertainment/24061821585/",
    title:
      "Single連続リリース、全国ツアー2024 ツアーファイナル…勢いが止まらない「高嶺のなでしこ」が登場！ – CMNOW WEB",
    authorName: "CMNOW WEB",
    publishedAt: "2024-07-16",
    mediaUrl: "https://cmnow.jp/entertainment/24061821585/",
    imageUrl: "https://cmnow.jp/wp-content/uploads/2024/06/DSC_7787s.jpg",
    category: "article",
    presents: ["春野莉々", "星谷美来", "松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://www.walkerplus.com/article/1205174/",
    title:
      "『高嶺のなでしこ』松本ももな「この曲を歌って可愛いを更新できるように頑張りたい」(1/2)｜ウォーカープラス",
    authorName: "ウォーカープラス（Walkerplus）",
    publishedAt: "2024-07-14",
    mediaUrl: "https://www.walkerplus.com/article/1205174/",
    imageUrl: "https://news.walkerplus.com/article/1205174/13231592_615.jpg",
    category: "article",
    presents: ["松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://strmweb.jp/archives/13455/",
    title:
      "高嶺のなでしこ「結成2周年 “橋本桃呼＆春野莉々＆日向端ひな”が笑顔で語ったステージへの熱意」INTERVIEW",
    authorName: "STREAM（ストリーム）",
    publishedAt: "2024-07-14",
    mediaUrl: "https://strmweb.jp/archives/13455/",
    imageUrl: "https://strmweb.jp/home/wp-content/uploads/2024/07/TAK3786.jpg",
    category: "article",
    presents: ["橋本桃呼", "春野莉々", "日向端ひな"],
  },
  {
    kind: "youtube",
    key: "y9seli9v8GE",
    title: "松本ももなちゃん Ank Rougeカタログメイキング♡",
    authorName: "Ank Rouge channel♡",
    publishedAt: "2024-07-11",
    mediaUrl: "https://youtu.be/y9seli9v8GE",
    imageUrl: "https://i.ytimg.com/vi/y9seli9v8GE/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな"],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_8_hyoushi/2024summer_event_2/",
    title: "Popteen ばちかわフェス2024チケット販売開始‼︎",
    authorName: "Popteen Media",
    publishedAt: "2024-07-02",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_8_hyoushi/2024summer_event_2/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/07/0629_event-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "aAE1tGG1iLg",
    title: "【大混乱】この中に嘘つきがいます！人狼は誰だっ！！【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-06-30",
    mediaUrl: "https://youtu.be/aAE1tGG1iLg",
    imageUrl: "https://i.ytimg.com/vi/aAE1tGG1iLg/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "jKqtH-d6whg",
    title:
      "【横山由依に続け！】高嶺のなでしこ・CANDY TUNE・OCHA NORMA・虹のコンキスタドール からリアクション芸を極めしアイドルが集結！アルピーにハマるのは誰だ！？ #まいにち賞レース",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2024-06-28",
    mediaUrl: "https://youtu.be/jKqtH-d6whg",
    imageUrl: "https://i.ytimg.com/vi/jKqtH-d6whg/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
    deleted: true,
  },
  {
    kind: "youtube",
    key: "qDWptqbPVDc",
    title: "【デビュー】超期待の新人がモデルデビュー!!初撮影でテンションMAX!!【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2024-06-22",
    mediaUrl: "https://youtu.be/qDWptqbPVDc",
    imageUrl: "https://i.ytimg.com/vi/qDWptqbPVDc/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_7_hyoushi/summer_coordinate_schooluniform/",
    title: "テーマ別 夏私服おひろめSNAP♡-放課後キャラ出し制服編-",
    authorName: "Popteen Media",
    publishedAt: "2024-06-17",
    mediaUrl:
      "https://popteen.co.jp/media/month_magazine/2024_7_hyoushi/summer_coordinate_schooluniform/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/06/c5693eb1b214a5f10bf7a634dbca8e8d-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/month_magazine/2024_7_hyoushi/creatormodeldebut/",
    title: "私たちもクリエイターモデルになりま〜す♡",
    authorName: "Popteen Media",
    publishedAt: "2024-06-03",
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_7_hyoushi/creatormodeldebut/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/06/1f0c4a3defccb5a72520668265f7128c-753x1024.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "dp7fYvkROYc",
    title: "酪農応援ニュース メイキング映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2024-06-01",
    mediaUrl: "https://youtu.be/dp7fYvkROYc",
    imageUrl: "https://i.ytimg.com/vi/dp7fYvkROYc/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "eEseLWatYxc",
    title: "【高嶺のなでしこ】たかねこ早口チャレンジvol.5(星谷美来×城月菜央)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2024-05-14",
    mediaUrl: "https://youtu.be/eEseLWatYxc",
    imageUrl: "https://i.ytimg.com/vi/eEseLWatYxc/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "星谷美来"],
  },
  {
    kind: "ogp",
    key: "https://mycolor.jp/michellmacaron/momonaM_item",
    title: "松本ももなｃ特集",
    authorName: "ファッション通販＆メディアMyColor ～マイカラー～",
    publishedAt: "2024-05-08",
    mediaUrl: "https://mycolor.jp/michellmacaron/momonaM_item",
    imageUrl: "https://mycolor.jp/assets-proxy/images/ogimage.png",
    category: "article",
    presents: ["松本ももな"],
  },
  {
    kind: "youtube",
    key: "0RKb9XMM_gI",
    title: "【高嶺のなでしこ】たかねこ早口チャレンジvol.4(葉月紗蘭×日向端ひな)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2024-05-07",
    mediaUrl: "https://youtu.be/0RKb9XMM_gI",
    imageUrl: "https://i.ytimg.com/vi/0RKb9XMM_gI/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭", "日向端ひな"],
  },
  {
    kind: "youtube",
    key: "4JkjAtXEUnM",
    title: "【高嶺のなでしこ】たかねこ早口チャレンジvol.3(東山恵里沙×春野莉々)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2024-05-07",
    mediaUrl: "https://youtu.be/4JkjAtXEUnM",
    imageUrl: "https://i.ytimg.com/vi/4JkjAtXEUnM/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々", "東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "Kp5Q_JVe8gU",
    title: "【高嶺のなでしこ】たかねこ早口チャレンジvol.2(松本ももな×籾山ひめり)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2024-04-23",
    mediaUrl: "https://youtu.be/Kp5Q_JVe8gU",
    imageUrl: "https://i.ytimg.com/vi/Kp5Q_JVe8gU/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "2cpJZZatVzs",
    title: "【高嶺のなでしこ】たかねこ早口チャレンジvol.1(涼海すう×橋本桃呼)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2024-04-16",
    mediaUrl: "https://youtu.be/2cpJZZatVzs",
    imageUrl: "https://i.ytimg.com/vi/2cpJZZatVzs/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "BsALipVzbfI",
    title: "【高嶺のなでしこ】運転免許トロッカクイズ 第1問！(涼海すう×橋本桃呼)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2024-04-16",
    mediaUrl: "https://youtu.be/BsALipVzbfI",
    imageUrl: "https://i.ytimg.com/vi/BsALipVzbfI/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "ogp",
    key: "https://nicola.jp/?p=19490",
    title:
      "【今気になる！ 令和最強ティーン】高嶺のなでしこ・東山恵里沙ちゃん｜TOPICS｜ニコラネット｜nicola公式サイト（新潮社）",
    authorName: "ニコラネット｜nicola公式サイト（新潮社）",
    publishedAt: "2024-04-07",
    mediaUrl: "https://nicola.jp/?p=19490",
    imageUrl: "https://nicola.jp/wp-content/uploads/2024/04/higashiyamaerisa_nico305-116-1.jpg",
    category: "article",
    presents: ["東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "fYPiZtEgAzY",
    title: "「ヒミツのミルクイズ」に高嶺のなでしこが挑戦　葉月紗蘭＆城月菜央 ver",
    authorName: "milkchapon",
    publishedAt: "2024-03-29",
    mediaUrl: "https://youtu.be/fYPiZtEgAzY",
    imageUrl: "https://i.ytimg.com/vi/fYPiZtEgAzY/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "fLbptjbKr5k",
    title: "「ヒミツのミルクイズ」に高嶺のなでしこが挑戦　松本ももな＆橋本桃呼 ver",
    authorName: "milkchapon",
    publishedAt: "2024-03-29",
    mediaUrl: "https://youtu.be/fLbptjbKr5k",
    imageUrl: "https://i.ytimg.com/vi/fLbptjbKr5k/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼", "松本ももな"],
  },
  {
    kind: "youtube",
    key: "cfB9IHTdQms",
    title: "「ヒミツのミルクイズ」に高嶺のなでしこが挑戦　日向端ひな＆籾山ひめり ver",
    authorName: "milkchapon",
    publishedAt: "2024-03-29",
    mediaUrl: "https://youtu.be/cfB9IHTdQms",
    imageUrl: "https://i.ytimg.com/vi/cfB9IHTdQms/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "gQtbellN6Ac",
    title: "「ヒミツのミルクイズ」に高嶺のなでしこが挑戦　東山恵里沙＆春野莉々 ver",
    authorName: "milkchapon",
    publishedAt: "2024-03-29",
    mediaUrl: "https://youtu.be/gQtbellN6Ac",
    imageUrl: "https://i.ytimg.com/vi/gQtbellN6Ac/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々", "東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "ZTVs_hs95lA",
    title: "「ヒミツのミルクイズ」に高嶺のなでしこが挑戦　星谷美来＆涼海すう ver",
    authorName: "milkchapon",
    publishedAt: "2024-03-29",
    mediaUrl: "https://youtu.be/ZTVs_hs95lA",
    imageUrl: "https://i.ytimg.com/vi/ZTVs_hs95lA/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "星谷美来"],
  },
  {
    kind: "youtube",
    key: "g2fJbed_0lY",
    title: "【酪農応援プロジェクト2024】　酪農応援ニュース　第3回",
    authorName: "ウェザーニュース",
    publishedAt: "2024-03-29",
    mediaUrl: "https://youtu.be/g2fJbed_0lY",
    imageUrl: "https://i.ytimg.com/vi/g2fJbed_0lY/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "L117TxKbKfE",
    title: "「酪農応援ニュース」第3回　リポート映像（北海道編）",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2024-03-28",
    mediaUrl: "https://youtu.be/L117TxKbKfE",
    imageUrl: "https://i.ytimg.com/vi/L117TxKbKfE/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "n2ywIfn16Y0",
    title: "「酪農応援ニュース」第2回　リポート映像（鹿児島編）",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2024-03-20",
    mediaUrl: "https://youtu.be/n2ywIfn16Y0",
    imageUrl: "https://i.ytimg.com/vi/n2ywIfn16Y0/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "日向端ひな"],
  },
  {
    kind: "youtube",
    key: "Dwwe9x-eYk8",
    title: "「酪農応援ニュース」第1回　リポート映像（岐阜編）",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2024-03-20",
    mediaUrl: "https://youtu.be/Dwwe9x-eYk8",
    imageUrl: "https://i.ytimg.com/vi/Dwwe9x-eYk8/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭", "東山恵里沙", "星谷美来"],
  },
  {
    kind: "youtube",
    key: "FYElLOWHNxg",
    title: "【酪農応援プロジェクト2024】　酪農応援ニュース　第2回",
    authorName: "ウェザーニュース",
    publishedAt: "2024-03-14",
    mediaUrl: "https://youtu.be/FYElLOWHNxg",
    imageUrl: "https://i.ytimg.com/vi/FYElLOWHNxg/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    key: "q6dVNOgjTik",
    title: "酪農応援プロジェクト2024　酪農応援ニュース　第1回",
    authorName: "ウェザーニュース",
    publishedAt: "2024-03-08",
    mediaUrl: "https://youtu.be/q6dVNOgjTik",
    imageUrl: "https://i.ytimg.com/vi/q6dVNOgjTik/hqdefault.jpg",
    category: "youtube",
    presents: ["星谷美来"],
  },
  {
    kind: "ogp",
    key: "https://nicola.jp/?p=18655",
    title:
      "【高嶺のなでしこ】メジャーデビューシングル『美しく生きろ／恋を知った世界』インタビュー！　新学年をむかえるティーンの読者へのメッセージも♡｜TOPICS｜ニコラネット｜nicola公式サイト（新潮社）",
    authorName: "ニコラネット｜nicola公式サイト（新潮社）",
    publishedAt: "2024-03-08",
    mediaUrl: "https://nicola.jp/?p=18655",
    imageUrl: "https://nicola.jp/wp-content/uploads/2024/03/takaneko_nicola.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "oo2BqViKCUc",
    title: "ミルクの時間　酪農特別授業",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2024-03-06",
    mediaUrl: "https://youtu.be/oo2BqViKCUc",
    imageUrl: "https://i.ytimg.com/vi/oo2BqViKCUc/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々", "東山恵里沙", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://nicola.jp/?p=18495",
    title:
      "【高嶺のなでしこ】メンバー全員の個人プロフ帳♡　学生時代のお決まりヘアアレから今後の夢まで、ぜーんぶ手描きで大公開♡｜TOPICS｜ニコラネット｜nicola公式サイト（新潮社）",
    authorName: "ニコラネット｜nicola公式サイト（新潮社）",
    publishedAt: "2024-03-01",
    mediaUrl: "https://nicola.jp/?p=18495",
    imageUrl: "https://nicola.jp/wp-content/uploads/2024/03/takaneko.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.radionikkei.jp/toraken/3.html",
    title:
      "第4回ゲスト研究員は引き続き、高嶺のなでしこ、東山恵里沙さんと葉月紗蘭さん！｜虎ノ門 トレンド経済研究所｜エンタメ・カルチャー｜ラジオNIKKEI",
    authorName: "ラジオNIKKEI",
    publishedAt: "2024-02-29",
    mediaUrl: "https://www.radionikkei.jp/toraken/3.html",
    imageUrl: "https://www.radionikkei.jp/toraken/images/IMG_0010.JPG",
    category: "audio",
    presents: ["葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1182799/",
    title:
      "高嶺のなでしこ、メジャーデビュー曲は「同じアイドルの人に聴いてほしい」 | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2024-02-28",
    mediaUrl: "https://thetv.jp/news/detail/1182799/",
    imageUrl: "https://thetv.jp/i/nw/1182799/12754860.jpg?w=1284",
    category: "article",
    presents: ["涼海すう", "葉月紗蘭", "春野莉々", "東山恵里沙"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1184512/",
    title:
      "高嶺のなでしこの強みは“十人十色”「10人のうち1人には虜になってもらえる」 | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2024-02-28",
    mediaUrl: "https://thetv.jp/news/detail/1184512/",
    imageUrl: "https://thetv.jp/i/nw/1184512/12754885.jpg?w=1284",
    category: "article",
    presents: ["城月菜央", "日向端ひな", "星谷美来"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1184513/",
    title:
      "高嶺のなでしこ、最終目標は“武道館”「美しく生きろ」でメジャーデビュー | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2024-02-28",
    mediaUrl: "https://thetv.jp/news/detail/1184513/",
    imageUrl: "https://thetv.jp/i/nw/1184513/12754905.jpg?w=1284",
    category: "article",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://xtrend.nikkei.com/atcl/contents/18/00962/00009/",
    title: "高嶺のなでしこ　女性人気でMV再生1300万超えの注目アイドル",
    authorName: "日経クロストレンド",
    publishedAt: "2024-02-22",
    mediaUrl: "https://xtrend.nikkei.com/atcl/contents/18/00962/00009/",
    imageUrl: "https://xtrend.nikkei.com/atcl/contents/18/00962/00009/nxr_m.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.radionikkei.jp/toraken/2.html",
    title:
      "第3回ゲスト研究員は高嶺のなでしこ、葉月紗蘭さんと東山恵里沙さん！｜虎ノ門 トレンド経済研究所｜エンタメ・カルチャー｜ラジオNIKKEI",
    authorName: "ラジオNIKKEI",
    publishedAt: "2024-02-22",
    mediaUrl: "https://www.radionikkei.jp/toraken/2.html",
    imageUrl: "https://www.radionikkei.jp/toraken/images/IMG_0002.JPG",
    category: "audio",
    presents: ["葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "ogp",
    key: "https://www.vanitymix.jp/music/takanenonadeshiko-2/",
    title: "高嶺のなでしこ VANITYMIX WEB LIMITED INTERVIEW",
    authorName: "VANITYMIX マガジン",
    publishedAt: "2024-02-21",
    mediaUrl: "https://www.vanitymix.jp/music/takanenonadeshiko-2/",
    imageUrl: "https://www.vanitymix.jp/wp-content/uploads/2024/02/takane_Aphoto_01-scaled.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.sanspo.com/article/20240213-DNGFPN44GBO7TA4OQBYGAB4BFU/",
    title:
      "高嶺のなでしこ、２１日メジャーデビュー　シングル「美しく生きろ／恋を知った世界」バスらせる",
    authorName: "サンスポ",
    publishedAt: "2024-02-13",
    mediaUrl: "https://www.sanspo.com/article/20240213-DNGFPN44GBO7TA4OQBYGAB4BFU/",
    imageUrl:
      "https://www.sanspo.com/resizer/v2/HEHZWGSFEVMZVFFSL42WL57U34.jpg?auth=2be87ebb5feadb183cb238d24204297ac527b5593da1a854fa8be9de4d9179db&quality=50&focal=2652%2C759&width=1200&height=630",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "4Pyi7Gk2IXI",
    title: "【柚姫の部屋 第237回】TEAM SHACHI大黒柚姫と瀬戸口俊介のほぼ月曜夜９時生配信",
    authorName: "TEAM SHACHI【公式】",
    publishedAt: "2024-02-05",
    mediaUrl: "https://youtu.be/4Pyi7Gk2IXI",
    imageUrl: "https://i.ytimg.com/vi/4Pyi7Gk2IXI/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "春野莉々"],
  },
  {
    kind: "ogp",
    key: "https://prtimes.jp/main/html/rd/p/000000561.000025517.html",
    title:
      "【オフィシャルレポート】高嶺のなでしこ 初の海外公演！『CONTEMPO：マカオ・ジャパン・スプリング・フェスティバル』のトップバッターを飾る",
    authorName: "プレスリリース・ニュースリリース配信シェアNo.1｜PR TIMES",
    publishedAt: "2024-02-05",
    mediaUrl: "https://prtimes.jp/main/html/rd/p/000000561.000025517.html",
    imageUrl:
      "https://prcdn.freetls.fastly.net/release_image/25517/561/25517-561-90cb30918cb9afc5ca2a4c69ca1bde43-3000x2000.jpg?format=jpeg&auto=webp&fit=bounds&width=2400&height=1260",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "mVaR9q39xYs",
    title: "高嶺のなでしこ 東山 恵里沙ちゃん Ank Rougeカタログメイキング",
    authorName: "Ank Rouge チャンネル",
    publishedAt: "2024-02-01",
    mediaUrl: "https://youtu.be/mVaR9q39xYs",
    imageUrl: "https://i.ytimg.com/vi/mVaR9q39xYs/hqdefault.jpg",
    category: "youtube",
    presents: ["東山恵里沙"],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://natalie.mu/music/column/558076",
    title: "女性アイドル / グループ編 | マイベストトラック2023 Vol. 1 - 音楽ナタリー コラム",
    authorName: "音楽ナタリー",
    publishedAt: "2024-01-24",
    mediaUrl: "https://natalie.mu/music/column/558076",
    imageUrl:
      "https://ogre.natalie.mu/media/news/music/2024/0122/besttrack2021_girlsgroup_card.jpg?impolicy=twitter_card_face_crop",
    category: "article",
    presents: ["松本ももな"],
  },
  {
    kind: "youtube",
    key: "D8RlMD4MGiE",
    title:
      "高嶺のなでしこ、「美しく生きろ」のM/V公開及びメジャーデビューを控えた感想インタビューを実施！",
    authorName: "WowKorea FAN",
    publishedAt: "2024-01-19",
    mediaUrl: "https://youtu.be/D8RlMD4MGiE",
    imageUrl: "https://i.ytimg.com/vi/D8RlMD4MGiE/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
];
