import { OgpMediaDescriptor } from "../types";

export const Ogp2024: OgpMediaDescriptor[] = [
  {
    mediaUrl: "https://abema.tv/video/episode/88-77_s1_p293",
    publishedAt: "2024-12-28",
    category: "video",
    presents: ["日向端ひな"],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/55859/",
    publishedAt: "2025-12-24",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://strmweb.jp/?p=15750",
    publishedAt: "2024-12-13",
    category: "article",
    presents: ["城月菜央", "東山恵里沙", "籾山ひめり"],
    officialTwitter: "https://x.com/takanenofficial/status/1867502445129347186",
  },
  {
    mediaUrl: "https://popteen.co.jp/media/57339/",
    publishedAt: "2025-12-12",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://www.radionikkei.jp/toraken/42_takakneko.html",
    publishedAt: "2024-12-11",
    category: "audio",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    mediaUrl: "https://www.walkerplus.com/article/1229695/",
    publishedAt: "2024-12-11",
    category: "article",
    presents: [],
    officialTwitter: "https://x.com/takanenofficial/status/1867140014792146977",
  },
  {
    mediaUrl: "https://recochoku.jp/ch/recolog/takanenonadeshiko/",
    publishedAt: "2024-12-11",
    category: "article",
    presents: ["城月菜央", "松本ももな", "籾山ひめり"],
    officialTwitter: "https://x.com/takanenofficial/status/1867124849006817746",
  },
  {
    mediaUrl: "https://popnroll.tv/articles/41644",
    publishedAt: "2024-12-11",
    siteName: "Pop'n'Roll",
    category: "article",
    presents: ["東山恵里沙", "松本ももな", "籾山ひめり"],
    officialTwitter: "https://x.com/takanenofficial/status/1866686924095885559",
  },
  {
    mediaUrl: "https://www.oricon.co.jp/news/2358400/",
    publishedAt: "2024-12-11",
    category: "article",
    presents: ["橋本桃呼", "東山恵里沙", "籾山ひめり"],
  },
  {
    mediaUrl: "https://www.oricon.co.jp/news/2357995/",
    publishedAt: "2024-12-08",
    category: "article",
    presents: [],
  },
  {
    mediaUrl: "https://www.radionikkei.jp/toraken/41nadeshiko.html",
    publishedAt: "2024-12-04",
    category: "audio",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    mediaUrl: "https://cmnow.jp/next/24110522772/",
    publishedAt: "2024-11-27",
    category: "article",
    presents: ["涼海すう", "橋本桃呼", "春野莉々"],
  },
  {
    mediaUrl: "https://abema.tv/video/episode/88-77_s1_p281",
    publishedAt: "2024-10-18",
    category: "video",
    presents: ["橋本桃呼"],
  },
  {
    mediaUrl: "https://abema.tv/video/episode/88-77_s1_p280",
    publishedAt: "2024-10-11",
    category: "video",
    presents: ["橋本桃呼"],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/autumn_uniformsnap/",
    publishedAt: "2024-09-15",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/charactergoods_present/",
    publishedAt: "2024-09-09",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/bachikawafes_part2/",
    publishedAt: "2024-09-09",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_10_hyoushi/bachikawafes_part1/",
    publishedAt: "2024-09-09",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_9_hyoushi/best_cosme/",
    publishedAt: "2024-08-01",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://nicola.jp/?p=22017",
    publishedAt: "2024-07-23",
    category: "article",
    presents: [],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_8_hyoushi/2024summer_event_2/",
    publishedAt: "2024-07-02",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl:
      "https://popteen.co.jp/media/month_magazine/2024_7_hyoushi/summer_coordinate_schooluniform/",
    publishedAt: "2024-06-17",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://popteen.co.jp/media/month_magazine/2024_7_hyoushi/creatormodeldebut/",
    publishedAt: "2024-06-03",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    mediaUrl: "https://nicola.jp/?p=19490",
    publishedAt: "2024-04-07",
    category: "article",
    presents: ["東山恵里沙"],
  },
  {
    mediaUrl: "https://nicola.jp/?p=18655",
    publishedAt: "2024-03-08",
    category: "article",
    presents: [],
  },
  {
    mediaUrl: "https://nicola.jp/?p=18495",
    publishedAt: "2024-03-01",
    category: "article",
    presents: [],
  },
  {
    mediaUrl: "https://www.radionikkei.jp/toraken/3.html",
    publishedAt: "2024-02-29",
    category: "audio",
    presents: ["葉月紗蘭", "東山恵里沙"],
  },
  {
    mediaUrl: "https://thetv.jp/news/detail/1182799/",
    publishedAt: "2024-02-28",
    category: "article",
    presents: ["涼海すう", "葉月紗蘭", "春野莉々", "東山恵里沙"],
  },
  {
    mediaUrl: "https://thetv.jp/news/detail/1184512/",
    publishedAt: "2024-02-28",
    category: "article",
    presents: ["城月菜央", "日向端ひな", "星谷美来"],
  },
  {
    mediaUrl: "https://thetv.jp/news/detail/1184513/",
    publishedAt: "2024-02-28",
    category: "article",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    mediaUrl: "https://www.radionikkei.jp/toraken/2.html",
    publishedAt: "2024-02-22",
    category: "audio",
    presents: ["葉月紗蘭", "東山恵里沙"],
  },
  {
    mediaUrl: "https://www.vanitymix.jp/music/takanenonadeshiko-2/",
    publishedAt: "2024-02-21",
    category: "article",
    presents: [],
  },
];
