import { MediaDetails } from "~/features/media/types";

export const metadata2025: MediaDetails[] = [
  {
    kind: "youtube",
    title: "【高嶺のなでしこ】ホールツアー名古屋公演に向けてコメント到着！",
    authorName: "SUNDAY FOLK PROMOTION",
    publishedAt: "2025-04-22",
    mediaUrl: "https://youtu.be/0Y8UVokoj3Y",
    imageUrl: "https://i.ytimg.com/vi/0Y8UVokoj3Y/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "高嶺のなでしこ・籾山ひめり&日向端ひな、ランウェイ出演でファッションポイントを明かす！十代の頃の思い出も赤裸々告白　『超十代2025』独占インタビュー",
    authorName: "oricon",
    publishedAt: "2025-04-22",
    mediaUrl: "https://youtu.be/K_IuWutpyyE",
    imageUrl: "https://i.ytimg.com/vi/K_IuWutpyyE/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    title:
      "高嶺のなでしこ・籾山ひめり、ティーン世代に金言「やっておきたいなっていう思い出は全部叶えた方がいい」　日向端ひなが“十代の思い出”明かす「今思うと勉強しなって感じなんですけど(笑)」【インタビュー】 ",
    authorName: "ORICON NEWS",
    publishedAt: "2025-04-22",
    mediaUrl: "https://www.oricon.co.jp/news/2380978/full/",
    imageUrl:
      "https://contents.oricon.co.jp/upimg/news/2381000/2380978/20250422_161105_p_o_94356142.jpg",
    category: "article",
    presents: ["日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    title:
      "#310：美女13人がノブを翻弄！よく寝てなかったら死んでたSP - チャンスの時間 - シーズン (バラエティ) | 無料動画・見逃し配信を見るなら | ABEMA",
    authorName: "ABEMA",
    publishedAt: "2025-04-20",
    mediaUrl: "https://abema.tv/video/episode/90-979_s1_p310",
    imageUrl:
      "https://image.p-c2-x.abema-tv.com/image/programs/90-979_s1_p310/thumb002.png?height=504&quality=75&version=1745201060&width=896",
    category: "video",
    presents: ["日向端ひな"],
  },
  {
    kind: "ogp",
    title: "【新連載】すぅにゃの推し活WORLD〜vol.1 「イチバン好きなのは魔界ノりりむチャン♡」",
    authorName: "Popteen Media",
    publishedAt: "2025-04-20",
    mediaUrl: "https://popteen.co.jp/media/66952/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/04/42a5088ec45b9b100b6da6f37d8328ed.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    title:
      "【アイドルの本気】鈴木愛理が高嶺のなでしこと「可愛くてごめん」ダンスレッスン！「ざまあ顔」披露で大盛り上がり！バラエティで滑った時の可愛い挽回方法は？【でしょでしょ‼︎】",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2025-04-19",
    mediaUrl: "https://youtu.be/1004tylNRQ8",
    imageUrl: "https://i.ytimg.com/vi/1004tylNRQ8/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    title: "【涼海すう編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-18",
    mediaUrl: "https://youtu.be/oVCvpyCwM3k",
    imageUrl: "https://i.ytimg.com/vi/oVCvpyCwM3k/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    title:
      "いざ、ワンマンライブへ！ 橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#4】",
    authorName: "Quick Japan",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/5OZY2qzgoCc",
    imageUrl: "https://i.ytimg.com/vi/5OZY2qzgoCc/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    title:
      "【高嶺のなでしこ】夏休みの合宿免許は運転免許トロッカ！で決まり★│人気につき予約へお早めにー！",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/IO4heh_HROY",
    imageUrl: "https://i.ytimg.com/vi/IO4heh_HROY/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title: "【城月菜央編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/FBD8_in-9oU",
    imageUrl: "https://i.ytimg.com/vi/FBD8_in-9oU/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    title:
      "【未公開映像】プロバスケ選手アイドルフェス出演1日密着！初出し裏側映像から大盛り上がりの本番ステージまでカメラが潜入しました【ロウルとアイドルフェス】",
    authorName: "川崎ブレイブサンダース",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/UIuRvdpud80",
    imageUrl: "https://i.ytimg.com/vi/UIuRvdpud80/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    title: "春はトレンドのミニスカデニムで愛されガールに♡【私服デニムSNAP③】",
    authorName: "Popteen Media",
    publishedAt: "2025-04-09",
    mediaUrl: "https://popteen.co.jp/media/65848/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/03/1-3.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    title: "モデル別♡韓国コスメ推しリップLIST",
    authorName: "Popteen Media",
    publishedAt: "2025-04-08",
    mediaUrl: "https://popteen.co.jp/media/65391/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/04/88bf539d49dcf477eadfe7d2def7b04a.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    title: "すぅにゃ、りんりん、せらぴーの束感まつげメイクレシピ",
    authorName: "Popteen Media",
    publishedAt: "2025-04-01",
    mediaUrl: "https://popteen.co.jp/media/66054/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/03/8708a4dcd621422ef95c489d5622fade-e1743394901211.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    title:
      "高嶺のなでしこ×酪農応援プロジェクト特集｜牛乳が酪農家から店頭に届くまでを描いた「ミルクの旅路」 - 音楽ナタリー 特集・インタビュー",
    authorName: "音楽ナタリー",
    publishedAt: "2025-03-28",
    mediaUrl: "https://natalie.mu/music/pp/churaku-takaneko02",
    imageUrl:
      "https://ogre.natalie.mu/media/pp/churaku-takaneko02/churaku-takaneko02_ogp2.jpg?imwidth=1280&imdensity=1",
    category: "article",
    presents: ["涼海すう", "葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "youtube",
    title:
      "【ラパルフェ＆高嶺のなでしこ】コロッケリスペクトコンビ(？)とVIVANT名コンビ(？)がクイズに挑戦！　#クイズ5GATES",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2025-03-24",
    mediaUrl: "https://youtu.be/VVa7yYcWNFs",
    imageUrl: "https://i.ytimg.com/vi/VVa7yYcWNFs/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    title:
      "たかねこ・松本ももなは「おりぼんの擬人化」一番オシャレなメンバーは？【IDOL RUNWAY COLLECTION 2025 Supported by TGC】",
    authorName: "【entax】編集部🪄",
    publishedAt: "2025-03-21",
    mediaUrl: "https://youtu.be/Tfc3b3CMao4",
    imageUrl: "https://i.ytimg.com/vi/Tfc3b3CMao4/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "【保育されちゃうアイドル!?】城月 菜央の保育士1日体験に密着【高嶺のなでしこ】【HoneyWorks】",
    authorName: "保育士バンク！チャンネル【公式】",
    publishedAt: "2025-03-21",
    mediaUrl: "https://youtu.be/X7uPByzLhSY",
    imageUrl: "https://i.ytimg.com/vi/X7uPByzLhSY/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    title:
      "高嶺のなでしこ、ランウェイ挑戦！橋本桃呼「本人は“おりぼんの擬人化”って自分のことを言っているんですけど…」|entax（エンタックス）",
    authorName: "entax（エンタックス）",
    publishedAt: "2025-03-21",
    mediaUrl: "https://www.entax.news/post/202503211900.html",
    imageUrl: "https://www.entax.news/wp-content/uploads/2025/03/1_4Z1A8800.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "「アイドルの責任」橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#3】",
    authorName: "Quick Japan",
    publishedAt: "2025-03-14",
    mediaUrl: "https://youtu.be/ep3Z2kpyfmQ",
    imageUrl: "https://i.ytimg.com/vi/ep3Z2kpyfmQ/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    title: "【高嶺のなでしこ】運転免許トロッカクイズ 第5問！(星谷美来×城月菜央)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-03-07",
    mediaUrl: "https://youtu.be/kNXz-Ai5lGA",
    imageUrl: "https://i.ytimg.com/vi/kNXz-Ai5lGA/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "星谷美来"],
  },
  {
    kind: "youtube",
    title: "ミルクの旅路　ダイジェスト版",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2025-03-06",
    mediaUrl: "https://youtu.be/EnGLaMDVNy4",
    imageUrl: "https://i.ytimg.com/vi/EnGLaMDVNy4/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "youtube",
    title: "ミルクの旅路",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2025-03-06",
    mediaUrl: "https://youtu.be/7m9f8omnNoM",
    imageUrl: "https://i.ytimg.com/vi/7m9f8omnNoM/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "youtube",
    title:
      "５時に夢中！スピンオフ特番 ミルクにモ～夢中！　TOKYO MX×ウェザーニュース×高嶺のなでしこ",
    authorName: "ウェザーニュース",
    publishedAt: "2025-03-06",
    mediaUrl: "https://youtu.be/_19fXNWKm9A",
    imageUrl: "https://i.ytimg.com/vi/_19fXNWKm9A/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "「もっと自分を好きになりたい」橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#2】",
    authorName: "Quick Japan",
    publishedAt: "2025-02-20",
    mediaUrl: "https://youtu.be/_qposQVQviw",
    imageUrl: "https://i.ytimg.com/vi/_qposQVQviw/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    title:
      "【高嶺のなでしこ】運転免許トロッカクイズ 第4問！(葉月紗蘭×日向端ひな)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-02-19",
    mediaUrl: "https://youtu.be/ftfQlE6dGxQ",
    imageUrl: "https://i.ytimg.com/vi/ftfQlE6dGxQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭", "日向端ひな"],
  },
  {
    kind: "youtube",
    title: "【ドラマ】「信じてたのに!!」親友に家族を壊された。",
    authorName: "CUL DRAMA / カルドラマ",
    publishedAt: "2025-02-15",
    mediaUrl: "https://youtu.be/RG7S6MunsWo",
    imageUrl: "https://i.ytimg.com/vi/RG7S6MunsWo/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々"],
  },
  {
    kind: "youtube",
    title:
      "【高嶺のなでしこ】運転免許トロッカクイズ 第3問！(東山恵里沙×春野莉々)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-02-12",
    mediaUrl: "https://youtu.be/UDB1pOUgmYA",
    imageUrl: "https://i.ytimg.com/vi/UDB1pOUgmYA/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々", "東山恵里沙"],
  },
  {
    kind: "youtube",
    title: "♡日向端ひなちゃん×Ank Rougeカタログメイキング♡",
    authorName: "Ank Rouge channel♡",
    publishedAt: "2025-02-06",
    mediaUrl: "https://youtu.be/kdXGcSF4xvI",
    imageUrl: "https://i.ytimg.com/vi/kdXGcSF4xvI/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    title:
      "「アイドル、向いてないかも」橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる #1】",
    authorName: "Quick Japan",
    publishedAt: "2025-02-05",
    mediaUrl: "https://youtu.be/JV_sPRXFHBA",
    imageUrl: "https://i.ytimg.com/vi/JV_sPRXFHBA/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "static",
    title:
      "②【先行掲載・WEBオリジナル記事】国立代々木第二体育館公演開催！！高嶺のなでしこ。総1万6,000字 ロング・インタビュー 前編、先行掲載！②",
    authorName: "OUT of MUSIC",
    publishedAt: "2025-02-04",
    mediaUrl: "https://outofmusic.net/?p=1540",
    imageUrl: "/media/2025/2025-02-04_OUT of MUSIC.webp",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "【高嶺のなでしこ】運転免許トロッカクイズ 第2問！(籾山ひめり×松本ももな)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-02-03",
    mediaUrl: "https://youtu.be/oOOs4VLYs_I",
    imageUrl: "https://i.ytimg.com/vi/oOOs4VLYs_I/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    title: "私たちの本当の思いを伝えます【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2025-02-01",
    mediaUrl: "https://youtu.be/cEUL8pCvSdA",
    imageUrl: "https://i.ytimg.com/vi/cEUL8pCvSdA/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    title: "束感まつ毛命のアイドルJK、『高嶺のなでしこ』のすぅにゃ",
    authorName: "Popteen Media",
    publishedAt: "2025-02-01",
    mediaUrl: "https://popteen.co.jp/media/61981/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/01/IMG_6469-e1738333842436.jpeg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "static",
    title: "有野屋書店 第32回 ゲスト 高嶺のなでしこ 日向端ひな・涼海すう",
    authorName: "FODプレミアム",
    publishedAt: "2025-01-31",
    mediaUrl: "https://fod.fujitv.co.jp/title/2c78/2c78120058/",
    imageUrl: "/media/2025/2025-01-31_有野屋書店.webp",
    category: "video",
    presents: ["涼海すう", "日向端ひな"],
  },
  {
    kind: "ogp",
    title:
      "🍭 【連載】高嶺のなでしこ 東山恵里沙「アイドルからしか得られない栄養素」vol.1：AVAM「幸福度の高いライブでした」 - Pop'n'Roll(ポップンロール)",
    authorName: "Pop'n'Roll",
    publishedAt: "2025-01-27",
    mediaUrl: "https://popnroll.tv/articles/42189",
    imageUrl:
      "https://img.popnroll.tv/uploads/news_item/image/42189/large__%E9%9B%86%E5%90%88_.jpeg",
    category: "article",
    presents: ["東山恵里沙"],
  },
  {
    kind: "youtube",
    title: "【高嶺のなでしこ】夏休みは運転免許トロッカ！で合宿免許に行こう♪│ご予約はお早めに☆",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-01-22",
    mediaUrl: "https://youtu.be/eSlN7odHbMY",
    imageUrl: "https://i.ytimg.com/vi/eSlN7odHbMY/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "【高嶺のなでしこ】大人気の春休みシーズン★運転免許トロッカ！で免許をGETしよう！│ご予約へ急げー！",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-01-22",
    mediaUrl: "https://youtu.be/ItE-wU39oVg",
    imageUrl: "https://i.ytimg.com/vi/ItE-wU39oVg/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    title: "なんでもRANKING スクール部門!",
    authorName: "Popteen Media",
    publishedAt: "2025-01-01",
    mediaUrl: "https://popteen.co.jp/media/58588/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/01/popranking_schoolICa-1.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    title: "POPモ・クリモの勝手に妄想イメージRANKING！",
    authorName: "Popteen Media",
    publishedAt: "2025-01-01",
    mediaUrl: "https://popteen.co.jp/media/59103/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/01/IMG_5007.jpeg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    title: "SNAP！POPモ19人のクリスマスコーデを一挙ご紹介♡",
    authorName: "Popteen Media",
    publishedAt: "2025-12-24",
    mediaUrl: "https://popteen.co.jp/media/55859/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/12/IMG_3517.jpeg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    title: "POPモクリスマスSNAPコーデ♡〜ちょいROCK界隈編〜",
    authorName: "Popteen Media",
    publishedAt: "2025-12-12",
    mediaUrl: "https://popteen.co.jp/media/57339/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/12/33-2.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
];
