import { MediaDetails } from "~/features/media/types";

export const metadata2025: MediaDetails[] = [
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/777508",
    title: "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第7回『富江』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2025-12-26",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/777508",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2025/12/777508_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://glassgirl.info/article/post-32354/",
    title:
      "【マンスリーアイドルコラム No.053】高嶺のなでしこ 日向端ひな #4「旅の始まりと たかねこのクルーたち！」（12月火曜日担当・全4回） | ガラスガール",
    authorName: "ガラスガール",
    publishedAt: "2025-12-23",
    mediaUrl: "https://glassgirl.info/article/post-32354/",
    imageUrl: "/media/2025/2025-12-02_ガラスガールコラム.jpg",
    category: "article",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    key: "ZClvrHRQ5fo",
    title: "高嶺のなでしこ、1stアルバム『見上げるたびに、恋をする』リリース―Skream!動画メッセージ",
    authorName: "skreamjapan",
    publishedAt: "2025-12-22",
    mediaUrl: "https://youtu.be/ZClvrHRQ5fo",
    imageUrl: "https://i.ytimg.com/vi/ZClvrHRQ5fo/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://skream.jp/news/2025/12/takanenonadeshiko_interview.php",
    title:
      'HoneyWorksサウンド・プロデュース、高嶺のなでしこのインタビュー＆動画メッセージ公開。"アイドルがアイドルのことを歌う"強さと矜持――1stアルバム『見上げるたびに、恋をする。』リリース',
    authorName: "Skream! 邦楽ロック・洋楽ロック ポータルサイト",
    publishedAt: "2025-12-22",
    mediaUrl: "https://skream.jp/news/2025/12/takanenonadeshiko_interview.php",
    imageUrl:
      "https://skream.jp/news/assets_c/2025/12/takanenonadeshiko_interview-thumb-1200xauto-243641.jpg",
    category: "article",
    presents: ["涼海すう", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://skream.jp/interview/2025/12/takanenonadeshiko.php",
    title: "高嶺のなでしこ | Skream! インタビュー",
    authorName: "Skream! 邦楽ロック・洋楽ロック ポータルサイト",
    publishedAt: "2025-12-22",
    mediaUrl: "https://skream.jp/interview/2025/12/takanenonadeshiko.php",
    imageUrl:
      "https://skream.jp/interview/assets_c/2025/12/takanenonadeshiko-thumb-500xauto-242937.jpg",
    category: "article",
    presents: ["涼海すう", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "bhd6b2aaqrw",
    title: "【番外編】結城りなSASUKEへの道〜アイドル予選会を振り返る〜",
    authorName: "ukkaチャンネル",
    publishedAt: "2025-12-21",
    mediaUrl: "https://youtu.be/bhd6b2aaqrw",
    imageUrl: "https://i.ytimg.com/vi/bhd6b2aaqrw/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://realsound.jp/2025/12/post-2243406.html",
    title:
      "高嶺のなでしこ、走り続けたからこそ見えた景色ーー『見上げるたびに、恋をする。』に刻まれた“物語”",
    authorName: "Real Sound｜リアルサウンド",
    publishedAt: "2025-12-20",
    mediaUrl: "https://realsound.jp/2025/12/post-2243406.html",
    imageUrl: "https://realsound.jp/wp-content/uploads/2025/12/20251219-takanenonadeshiko-99.jpg",
    category: "article",
    presents: ["城月菜央", "葉月紗蘭", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.oricon.co.jp/news/2425639/full/",
    title:
      "高嶺のなでしこ、初アルバムで3年間の成長を総括　メンバーが語る未来への抱負【インタビュー】 ",
    authorName: "オリコンニュース（ORICON NEWS）",
    publishedAt: "2025-12-19",
    mediaUrl: "https://www.oricon.co.jp/news/2425639/full/",
    imageUrl:
      "https://contents.oricon.co.jp/upimg/news/2426000/2425639/20251218_102626_p_o_67545018.jpg",
    category: "article",
    presents: ["橋本桃呼", "東山恵里沙", "松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://rockinon.com/interview/detail/213869",
    title:
      "【インタビュー】かわいさもかっこよさも、強さも弱さも表現するアイドル、高嶺のなでしこ。HoneyWorksと歩んだ軌跡の詰まった1stフルアルバム『見上げるたびに、恋をする。』を語る－rockinon.com｜https://rockinon.com/interview/detail/213869",
    authorName: "rockinon.com",
    publishedAt: "2025-12-18",
    mediaUrl: "https://rockinon.com/interview/detail/213869",
    imageUrl: "https://rockinon.com/images/entry/width:1200/213869/1",
    category: "article",
    presents: ["城月菜央", "橋本桃呼", "東山恵里沙"],
  },
  {
    kind: "ogp",
    key: "https://natalie.mu/music/pp/takaneko",
    title:
      "高嶺のなでしこ インタビュー｜1stアルバム「見上げるたびに、恋をする。」は“戦友”と駆け抜けた青春の証 - 音楽ナタリー 特集・インタビュー",
    authorName: "音楽ナタリー",
    publishedAt: "2025-12-17",
    mediaUrl: "https://natalie.mu/music/pp/takaneko",
    imageUrl: "https://ogre.natalie.mu/media/pp/takaneko/takaneko_ogp.jpg?imwidth=1280&imdensity=1",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.vanitymix.jp/music/takanenonadeshiko-6/",
    title: "高嶺のなでしこ VANITYMIX WEB LIMITED INTERVIEW",
    authorName: "VANITYMIX マガジン",
    publishedAt: "2025-12-16",
    mediaUrl: "https://www.vanitymix.jp/music/takanenonadeshiko-6/",
    imageUrl:
      "https://www.vanitymix.jp/wp-content/uploads/2025/12/高嶺のなでしこ_アーティスト写真-e1765522902830.jpg",
    category: "article",
    presents: ["葉月紗蘭", "星谷美来", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://glassgirl.info/article/post-32229/",
    title:
      "【マンスリーアイドルコラム No.053】高嶺のなでしこ 日向端ひな #3「オーディション。そしてアニメ化希望」（12月火曜日担当・全4回） | ガラスガール",
    authorName: "ガラスガール",
    publishedAt: "2025-12-16",
    mediaUrl: "https://glassgirl.info/article/post-32229/",
    imageUrl: "/media/2025/2025-12-02_ガラスガールコラム.jpg",
    category: "article",
    presents: ["日向端ひな"],
  },
  {
    kind: "ogp",
    key: "https://rhp.nagoya/event/entry-928.html",
    title:
      "12月15日（月）～12月21日（日）高嶺のなでしこのMVを特集！ | イベント情報 | Hisaya-odori Park（久屋大通公園）",
    authorName: "Hisaya-odori Park（久屋大通公園）",
    publishedAt: "2025-12-15",
    mediaUrl: "https://rhp.nagoya/event/entry-928.html",
    imageUrl:
      "https://rhp.nagoya/archives/001/202512/ffdf4367faf5a08b4630263ab571c10817a44806ebcc068054a3101dea6acb4b.png",
    category: "article",
    presents: [],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://beeeem.com/article/takanekobf01",
    title:
      "高嶺のなでしこ【BEEEEM FES vol.1ライブレポート】“気高く美しい華”が舞った、可憐と熱情が交差する瞬間-BEEEEM",
    authorName: "BEEEEM",
    publishedAt: "2025-12-13",
    mediaUrl: "https://beeeem.com/article/takanekobf01",
    imageUrl:
      "https://imagedelivery.net/GAZ6B7nYxar6-1ZqFjo_3w/39b2d958-497c-45f5-e24f-8708bd883900/medium",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "m3u44cVIaq0",
    title:
      "＃９【混戦優勝争い】#風見和香 リベンジへ！女王 #伊藤実希 の逆襲は？佐藤莉華 ・塩釜菜那 初出場二人のタイムは？SASUKE出場権を懸けた最終決戦！",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-12-12",
    mediaUrl: "https://youtu.be/m3u44cVIaq0",
    imageUrl: "https://i.ytimg.com/vi/m3u44cVIaq0/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "ogp",
    key: "https://utaten.com/specialArticle/index/9685",
    title:
      "【2025年12月版】UtaTenが注目するアーティスト6選！編集部が気になるアーティストを紹介！アーティストからのコメントも！ | 歌詞検索サイト【UtaTen】ふりがな付",
    authorName: "UtaTen",
    publishedAt: "2025-12-12",
    mediaUrl: "https://utaten.com/specialArticle/index/9685",
    imageUrl:
      "https://cdn.utaten.com/uploads/images/specialArticle/9685/c743d3d3e815232f4da2d60668ccce1762cf8999.jpeg?r=2026020122",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "lvaSQ3VWDUg",
    title: "【高嶺のなでしこ】UtaTen注目アーティスト2025年12月コメント動画",
    authorName: "UtaTen",
    publishedAt: "2025-12-09",
    mediaUrl: "https://youtu.be/lvaSQ3VWDUg",
    imageUrl: "https://i.ytimg.com/vi/lvaSQ3VWDUg/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://glassgirl.info/article/post-31962/",
    title:
      "【マンスリーアイドルコラム No.053】高嶺のなでしこ 日向端ひな #2「ボイトレレッスンと死神」（12月火曜日担当・全4回） | ガラスガール",
    authorName: "ガラスガール",
    publishedAt: "2025-12-09",
    mediaUrl: "https://glassgirl.info/article/post-31962/",
    imageUrl: "/media/2025/2025-12-02_ガラスガールコラム.jpg",
    category: "article",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    key: "FJQ2wK1_vho",
    title:
      "＃8【最終種目】SASUKEタイムレース究極スピード決戦①試されるSASUKE力 衝撃の記録誕生！SASUKE出場権を掴むのは？　#SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-12-05",
    mediaUrl: "https://youtu.be/FJQ2wK1_vho",
    imageUrl: "https://i.ytimg.com/vi/FJQ2wK1_vho/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "ogp",
    key: "https://glassgirl.info/article/post-31830/",
    title:
      "【マンスリーアイドルコラム No.053・初週のみ無料公開】高嶺のなでしこ 日向端ひな #1「ひなたま、コラムはじめます！」（12月火曜日担当・全4回） | ガラスガール",
    authorName: "ガラスガール",
    publishedAt: "2025-12-02",
    mediaUrl: "https://glassgirl.info/article/post-31830/",
    imageUrl: "/media/2025/2025-12-02_ガラスガールコラム.jpg",
    category: "article",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    key: "yawFIcRTKv0",
    title:
      "＃７【激突】パワーフォース最終決戦！レジェンド驚愕の結末！力を制したのは？ #SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-28",
    mediaUrl: "https://youtu.be/yawFIcRTKv0",
    imageUrl: "https://i.ytimg.com/vi/yawFIcRTKv0/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "mfukppFWq58",
    title:
      "＃６【死闘】歴史的名勝負 パワー対決！決勝に勝ち上がるのは？ パワーフォース2回戦 #SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-28",
    mediaUrl: "https://youtu.be/mfukppFWq58",
    imageUrl: "https://i.ytimg.com/vi/mfukppFWq58/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/775621",
    title:
      "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第6回『新感染 ファイナル・エクスプレス』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2025-11-26",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/775621",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2025/11/775621_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "KafMweYmrBQ",
    title:
      "#５ 【パワー勝負】新種目パワーフォース　力と力がぶつかる パワー対決を制するのは？-1回戦- #SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-21",
    mediaUrl: "https://youtu.be/KafMweYmrBQ",
    imageUrl: "https://i.ytimg.com/vi/KafMweYmrBQ/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "L5i5JroVJ3s",
    title:
      "【応援メンバーも大熱狂】SASUKEアイドル予選会 第2種目配信開始🔥 #橋本桃呼 #桜木心菜 #高嶺のなでしこ #私立恵比寿中学",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-14",
    mediaUrl: "https://youtu.be/L5i5JroVJ3s",
    imageUrl: "https://i.ytimg.com/vi/L5i5JroVJ3s/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "bbz9D8CRv2I",
    title:
      "#4 【究極スタミナ決戦】新種目テイルインポッシブル ラスト１周で劇的ドラマ アイドルの意地激突 #SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-14",
    mediaUrl: "https://youtu.be/bbz9D8CRv2I",
    imageUrl: "https://i.ytimg.com/vi/bbz9D8CRv2I/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "F5qjrBtF9lo",
    title:
      "#3 【決着】アイドル最速女王決定戦 ビーチフラッグスを制したのは？SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-07",
    mediaUrl: "https://youtu.be/F5qjrBtF9lo",
    imageUrl: "https://i.ytimg.com/vi/F5qjrBtF9lo/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "ITv1oj8eQo0",
    title:
      "#2 【激戦区】スピード決戦！去年女王・結城&準優勝・大信田ら実力者たちがいきなり激突！SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-07",
    mediaUrl: "https://youtu.be/ITv1oj8eQo0",
    imageUrl: "https://i.ytimg.com/vi/ITv1oj8eQo0/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "yVbwPMKHWTg",
    title:
      "#1 【激闘開幕】SASUKE出場権を懸けた12名のアイドルたちのサバイバル開幕  SASUKEアイドル予選会2025",
    authorName: "SASUKE Ninja Warrior【TBS公式】SASUKEチャンネル",
    publishedAt: "2025-11-07",
    mediaUrl: "https://youtu.be/yVbwPMKHWTg",
    imageUrl: "https://i.ytimg.com/vi/yVbwPMKHWTg/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/78627/",
    title: "【最終回】すぅにゃの推し活WORLD♡いままでの軌跡をプレイバック★",
    authorName: "Popteen Media",
    publishedAt: "2025-11-07",
    mediaUrl: "https://popteen.co.jp/media/78627/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/11/ae46b1f460ee46f789c27b264a6cb421.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "BDGAjmWG0Rs",
    title: "個性爆発！「高嶺のなでしこ」の悩みとは【音楽マシマシ 2025.7.28OA】",
    authorName: "HBCラジオ公式YouTubeチャンネル",
    publishedAt: "2025-10-26",
    mediaUrl: "https://youtu.be/BDGAjmWG0Rs",
    imageUrl: "https://i.ytimg.com/vi/BDGAjmWG0Rs/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/772949",
    title:
      "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第5回『アダムス・ファミリー』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2025-10-25",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/772949",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2025/10/772949_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "TsFMmZcPH70",
    title:
      "【オリジナル楽曲】ときのそら「バチャリアラブ feat. 涼海すう&籾山ひめり from 高嶺のなでしこ」【Official Music Video】",
    authorName: "ときのそら",
    publishedAt: "2025-10-10",
    mediaUrl: "https://youtu.be/TsFMmZcPH70",
    imageUrl: "https://i.ytimg.com/vi/TsFMmZcPH70/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/77712/",
    title: "現役アイドル直伝の目立つ推し活グッズ♩すぅにゃの推し活WORLD♡Vol.7",
    authorName: "Popteen Media",
    publishedAt: "2025-10-10",
    mediaUrl: "https://popteen.co.jp/media/77712/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/10/insta1009-b.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "F78hD6G0hQw",
    title:
      "【推しに会えた園児の反応は…】現役アイドル籾山ひめりが保育士に挑戦！【高嶺のなでしこ】【HoneyWorks】",
    authorName: "保育士バンク！チャンネル【公式】",
    publishedAt: "2025-10-06",
    mediaUrl: "https://youtu.be/F78hD6G0hQw",
    imageUrl: "https://i.ytimg.com/vi/F78hD6G0hQw/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/77345/",
    title: "大谷・竹パラ・しなこチャン・ディズニーのあの名作も♡【ハロコスVol.3】",
    authorName: "Popteen Media",
    publishedAt: "2025-10-02",
    mediaUrl: "https://popteen.co.jp/media/77345/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/09/cfa8b3e1fa50b36f2dba85e72feba21e.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/770339",
    title:
      "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第4回『Five Nights at Freddy’s』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2025-09-29",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/770339",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2025/09/770339_04.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/76726",
    title: "ヒトリ遊びの天才になるコト。すぅにゃの推し活WORLD♡Vol.6",
    authorName: "Popteen Media",
    publishedAt: "2025-09-25",
    mediaUrl: "https://popteen.co.jp/media/76726",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/09/cd32e84e8cf21b59cb2e7426586cb3af.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://realsound.jp/2025/09/post-2154271.html",
    title:
      "高嶺のなでしこが刻んだ“誇り高きアイドル” としての矜持　新章へと向かうデビュー3周年記念ライブを観て",
    authorName: "Real Sound｜リアルサウンド",
    publishedAt: "2025-09-17",
    mediaUrl: "https://realsound.jp/2025/09/post-2154271.html",
    imageUrl: "https://realsound.jp/wp-content/uploads/2025/09/20250912-takaneko-99.jpg",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "youtube",
    key: "cv5gFafJ4tU",
    title:
      "高嶺のなでしこ、9人の覚悟。3rdファンミーティングに密着！橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#7】",
    authorName: "Quick Japan",
    publishedAt: "2025-09-11",
    mediaUrl: "https://youtu.be/cv5gFafJ4tU",
    imageUrl: "https://i.ytimg.com/vi/cv5gFafJ4tU/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "a1Gbr4LLqnc",
    title:
      "高嶺のなでしこ、初の韓国ワンマンライブ！橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#6】",
    authorName: "Quick Japan",
    publishedAt: "2025-09-08",
    mediaUrl: "https://youtu.be/a1Gbr4LLqnc",
    imageUrl: "https://i.ytimg.com/vi/a1Gbr4LLqnc/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "ar-v2exx9a0",
    title:
      "全国のホテルで楽しめるイマーシブサウンドアトラクション「変な部屋」を【高嶺のなでしこ】城月菜央 が体験！！",
    authorName: "imavo",
    publishedAt: "2025-09-05",
    mediaUrl: "https://youtu.be/ar-v2exx9a0",
    imageUrl: "https://i.ytimg.com/vi/ar-v2exx9a0/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "dmYhpOLT7hg",
    title:
      "【ファンミ独占密着】高嶺のなでしこ3周年“9人で立つ大舞台”籾山ひめり「私たちの覚悟を」ファンへのメッセージほぼノーカット＆浴衣で『可愛くてごめん』披露！新曲リハ映像＆ケータリング食リポも",
    authorName: "めざましmedia",
    publishedAt: "2025-09-01",
    mediaUrl: "https://youtu.be/dmYhpOLT7hg",
    imageUrl: "https://i.ytimg.com/vi/dmYhpOLT7hg/hqdefault.jpg",
    category: "youtube",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://wpb.shueisha.co.jp/news/entertainment/2025/08/31/128129/",
    title:
      "幕張メッセイベントホールでの3周年ライブを控える「高嶺のなでしこ」に直撃！　籾山ひめりの母性が爆発!?",
    authorName: "週プレNEWS［週刊プレイボーイのニュースサイト］",
    publishedAt: "2025-08-31",
    mediaUrl: "https://wpb.shueisha.co.jp/news/entertainment/2025/08/31/128129/",
    imageUrl: "https://wpb.shueisha.co.jp/news/entertainment/2025/images/Takanenonadeshiko01.jpg",
    category: "article",
    presents: ["城月菜央", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "941-Y6Kf1vI",
    title:
      "【総勢268人のアイドルが出演】TIF15年目なので”15秒”でお題に答えてもらいました！一発ギャグ・もしもアイドルじゃなかったら？・アイドル界でNo.1なこと・推しへの愛♥",
    authorName: "めざましmedia",
    publishedAt: "2025-08-30",
    mediaUrl: "https://youtu.be/941-Y6Kf1vI",
    imageUrl: "https://i.ytimg.com/vi/941-Y6Kf1vI/hqdefault.jpg",
    category: "youtube",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/766262",
    title:
      "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第3回『ザ・ウォッチャーズ』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2025-08-30",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/766262",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2025/08/766262_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1289131/",
    title:
      "高嶺のなでしこ「新曲『この世界は嘘でできている』は私たちの“勝負曲”」、9人体制で迎える幕張ライブへの思い | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2025-08-28",
    mediaUrl: "https://thetv.jp/news/detail/1289131/",
    imageUrl: "https://thetv.jp/i/nw/1289131/15191516.jpg?w=1284",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://prtimes.jp/main/html/rd/p/000000796.000025517.html",
    title:
      "【オフィシャルレポート】高嶺のなでしこ 広州・上海に続き、ソウル初のワンマンライブもチケット完売！延べ約1",
    authorName: "プレスリリース・ニュースリリース配信シェアNo.1｜PR TIMES",
    publishedAt: "2025-08-28",
    mediaUrl: "https://prtimes.jp/main/html/rd/p/000000796.000025517.html",
    imageUrl:
      "https://prcdn.freetls.fastly.net/release_image/25517/796/25517-796-f74cebd72d7310cb5b44fa0635250a4f-3900x2925.jpg?format=jpeg&auto=webp&fit=bounds&width=2400&height=1260",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "youtube",
    key: "o-whMm-I3Xg",
    title:
      "【閲覧注意】ななまがり&トム・ブラウン考案の超個性的行動がヤバすぎた※あくまでコントです※ゲスト：阿部なつき/水野舞菜/橋本桃呼（高嶺のなでしこ）【パクチーテレビ】",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2025-08-27",
    mediaUrl: "https://youtu.be/o-whMm-I3Xg",
    imageUrl: "https://i.ytimg.com/vi/o-whMm-I3Xg/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://wanibooks-newscrunch.com/articles/-/5839",
    title:
      "この夏を超えて・・・。高嶺のなでしこメンバー3人が語る3rd ANNIVERSARY CONCERT。 | WANI BOOKS Newsクランチ！（ニュースクランチ！）",
    authorName: "WANI BOOKS Newsクランチ！（ニュースクランチ！）",
    publishedAt: "2025-08-26",
    mediaUrl: "https://wanibooks-newscrunch.com/articles/-/5839",
    imageUrl:
      "https://wanibooks.ismcdn.jp/mwimgs/c/1/750m/img_c1c8a539d975a5571ff8c514816e6c8a2619253.jpg",
    category: "article",
    presents: ["東山恵里沙", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/75459/",
    title: "好きなクリープハイプで眠る夜も♡すぅにゃの推し活WORLD！Vol.5",
    authorName: "Popteen Media",
    publishedAt: "2025-08-22",
    mediaUrl: "https://popteen.co.jp/media/75459/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/08/d1d3cb0c114a6ad55d53b993a2dde33d-1024x1024.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://spice.eplus.jp/articles/340073",
    title:
      "高嶺のなでしこ　寸劇あり、ゲームあり、華麗に魅せるライブパフォーマンスあり、3rdファンミーティングで届けた9人の覚悟 | SPICE - エンタメ特化型情報メディア スパイス",
    authorName: "SPICE（スパイス）｜エンタメ特化型情報メディア スパイス",
    publishedAt: "2025-08-19",
    mediaUrl: "https://spice.eplus.jp/articles/340073",
    imageUrl:
      "https://spice.eplus.jp/images/exknA8JHG36FxqwqUbzAARJlCcNVJ1uSvIWLyGi7lsAMiJSakqae7IWEvpXksQaJ",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://news.mynavi.jp/article/20250813-3405171/",
    title:
      "『SASUKE』本戦出場をかけアイドル12人が勝負「てっぺん取りたい」「グループとしてもいい風を」",
    authorName: "マイナビニュース",
    publishedAt: "2025-08-13",
    mediaUrl: "https://news.mynavi.jp/article/20250813-3405171/",
    imageUrl: "https://news.mynavi.jp/article/20250813-3405171/ogp_images/ogp.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://kaiwaiweb.com/news/13369/",
    title: "江嶋綾恵梨が切り撮る『TIF2025』高嶺のなでしこ編 - BEEEEM（ビーーーム）",
    authorName: "BEEEEM（ビーーーム）",
    publishedAt: "2025-08-13",
    mediaUrl: "https://kaiwaiweb.com/news/13369/",
    imageUrl: "https://kaiwaiweb.com/wp/wp-content/uploads/2025/08/DSCF6865.jpg",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://www.lvtimes.net/broad/71117/",
    title: "高嶺のなでしこ、切なさ・力強さ・ファンとの一体感を感じさせるステージ！＜TIF2025＞",
    authorName: "Liveen Times",
    publishedAt: "2025-08-04",
    mediaUrl: "https://www.lvtimes.net/broad/71117/",
    imageUrl: "https://www.lvtimes.net/wp-content/uploads/2025/08/AY5R2560.jpg",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://horror2.jp/74779",
    title:
      "城月菜央（高嶺のなでしこ）が「恐怖心展」を体験！　「恐怖が感情だけでなく思考にも訴えてくる」",
    authorName: "ホラー通信",
    publishedAt: "2025-08-04",
    mediaUrl: "https://horror2.jp/74779",
    imageUrl: "https://horror2.jp/files/2025/07/S__13049871_0.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "WmJC13ijUU8",
    title:
      "高嶺のなでしこ・城月菜央が、絶叫お化け屋敷に行ってみた👻映画「事故物件ゾク 恐い間取り」❌台場怪奇学校コラポ",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-08-03",
    mediaUrl: "https://youtu.be/WmJC13ijUU8",
    imageUrl: "https://i.ytimg.com/vi/WmJC13ijUU8/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1282854/",
    title:
      "高嶺のなでしこ、“初恋”をつなぐセットリストでストーリーを感じる熱いステージを展開＜TIF2025＞ | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2025-08-03",
    mediaUrl: "https://thetv.jp/news/detail/1282854/",
    imageUrl: "https://thetv.jp/i/nw/1282854/15036183.jpg?w=1284",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://www.lvtimes.net/broad/70992/",
    title: "高嶺のなでしこ、青春の疾走感と“かわいい”の全開放！＜TIF2025＞",
    authorName: "Liveen Times",
    publishedAt: "2025-08-03",
    mediaUrl: "https://www.lvtimes.net/broad/70992/",
    imageUrl: "https://www.lvtimes.net/wp-content/uploads/2025/08/AY5R1855.jpg",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "ogp",
    key: "https://mezamashi.media/articles/181920",
    title:
      "あなたの推しも？撮り下ろしTOKYO IDOL FESTIVAL(TIF) 2025 2日目出演アイドルによるファンに向けた15文字のラブレターを掲載！ | めざましmedia | “好き”でつながる",
    authorName: "めざましmedia",
    publishedAt: "2025-08-02",
    mediaUrl: "https://mezamashi.media/articles/181920",
    imageUrl:
      "https://mezamashi.ismcdn.jp/mwimgs/8/2/1200xm/img_828be727b9ed2ecdd2449817a3f54948242018.jpg",
    category: "article",
    presents: ["高嶺のなでしこ2"],
  },
  {
    kind: "youtube",
    key: "xQvYJoyIzjs",
    title: "【8月1日公開】♥Jamieエーエヌケー×籾山ひめりちゃん撮影メイキング♥",
    authorName: "Jamieエーエヌケーchannel♥",
    publishedAt: "2025-07-31",
    mediaUrl: "https://youtu.be/xQvYJoyIzjs",
    imageUrl: "https://i.ytimg.com/vi/xQvYJoyIzjs/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり"],
    deleted: true,
  },
  {
    kind: "youtube",
    key: "eyoa2_NU138",
    title: "【8月1日公開】♡Ank Rouge×籾山ひめりちゃんカタログメイキング♡",
    authorName: "Ank Rouge channel♡",
    publishedAt: "2025-07-31",
    mediaUrl: "https://youtu.be/eyoa2_NU138",
    imageUrl: "https://i.ytimg.com/vi/eyoa2_NU138/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり"],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://kaiwaiweb.com/news/12965/",
    title:
      "【六本木アイドルフェスティバル2025ライブレポート】高嶺のなでしこ、大トリで好きが溢れる圧巻のステージ - BEEEEM（ビーーーム）",
    authorName: "BEEEEM（ビーーーム）",
    publishedAt: "2025-07-31",
    mediaUrl: "https://kaiwaiweb.com/news/12965/",
    imageUrl:
      "https://kaiwaiweb.com/wp/wp-content/uploads/2025/07/takanekosama_RIF2025_029-watermarked.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://bezzy.jp/2025/07/70604/",
    title: "強みを磨いてグループ史上最大の挑戦へ、この夏を駆ける高嶺のなでしこの全力宣言",
    authorName: "Bezzy［ベジー］｜「人の魅力」にフォーカスしたエンタメメディア",
    publishedAt: "2025-07-31",
    mediaUrl: "https://bezzy.jp/2025/07/70604/",
    imageUrl: "https://bezzy.jp/cms/wp-content/uploads/2025/07/0961-1200x800.jpg",
    category: "article",
    presents: ["橋本桃呼", "葉月紗蘭", "東山恵里沙", "松本ももな"],
  },
  {
    kind: "youtube",
    key: "MgLRfWyECfc",
    title:
      "【ショートドラマ】住みますアイドル 事故物件4日目丑三つ時　映画「事故物件ゾク 恐い間取り」コラボ　＃事故物件　#映画　#ホラー",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-29",
    mediaUrl: "https://youtu.be/MgLRfWyECfc",
    imageUrl: "https://i.ytimg.com/vi/MgLRfWyECfc/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "AhZRc8xVM-Y",
    title:
      "【ショートドラマ】住みますアイドル　事故物件4日目　映画「事故物件ゾク 恐い間取り」コラボ",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-28",
    mediaUrl: "https://youtu.be/AhZRc8xVM-Y",
    imageUrl: "https://i.ytimg.com/vi/AhZRc8xVM-Y/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "JK3sm50DW10",
    title:
      "日本ペイントマレッツ vs 日本生命レッドエルフ ノジマTリーグ2025-2026女子開幕戦 2025年07月27日(日) 14:00試合開始 代々木第二体育館 開幕戦直前スペシャル13時配信スタート",
    authorName: "【公式】卓球Tリーグ公式サイト",
    publishedAt: "2025-07-27",
    mediaUrl: "https://youtu.be/JK3sm50DW10",
    imageUrl: "https://i.ytimg.com/vi/JK3sm50DW10/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "m8A3u4l-UdE",
    title:
      "【ショートドラマ】住みますアイドル　事故物件3日目　映画「事故物件ゾク 恐い間取り」コラボ　＃事故物件　＃ホラー　＃高嶺のなでしこ",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-27",
    mediaUrl: "https://youtu.be/m8A3u4l-UdE",
    imageUrl: "https://i.ytimg.com/vi/m8A3u4l-UdE/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "tpwwctmr2uk",
    title:
      "【ショートドラマ】住みますアイドル　事故物件2日目　映画「事故物件ゾク 恐い間取り」コラボ",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-26",
    mediaUrl: "https://youtu.be/tpwwctmr2uk",
    imageUrl: "https://i.ytimg.com/vi/tpwwctmr2uk/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "7A0NcPz3Exs",
    title:
      "【ショートドラマ】住みますアイドル　事故物件1日目　映画「事故物件ゾク 恐い間取り」コラボ",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-25",
    mediaUrl: "https://youtu.be/7A0NcPz3Exs",
    imageUrl: "https://i.ytimg.com/vi/7A0NcPz3Exs/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "UfzRlI0z2SI",
    title:
      "【ショートドラマ】住みますアイドル　事故物件0日目　映画「事故物件ゾク 恐い間取り」コラボショートドラマ　　＃高嶺のなでしこ　＃城月菜央　＃ホラーちゃんねる",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-24",
    mediaUrl: "https://youtu.be/UfzRlI0z2SI",
    imageUrl: "https://i.ytimg.com/vi/UfzRlI0z2SI/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "hsHkiXBgm38",
    title: "【予告】「事故物件住みますアイドル」コラボショートドラマがホラーちゃんねるにて独占配信",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-23",
    mediaUrl: "https://youtu.be/hsHkiXBgm38",
    imageUrl: "https://i.ytimg.com/vi/hsHkiXBgm38/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://nonno.hpplus.jp/entertainment/interview/261409/",
    title:
      "高嶺のなでしこ 橋本桃呼・東山恵里沙・松本ももな 『ライフクエスト』配信中。3人がごほうびに選ぶものは？ | インタビュー | non-no web",
    authorName: "non-no web",
    publishedAt: "2025-07-21",
    mediaUrl: "https://nonno.hpplus.jp/entertainment/interview/261409/",
    imageUrl: "https://nonno.hpplus.jp/wp-content/uploads/8217d37079ef2ebc77d9de973e1ff168.jpg",
    category: "article",
    presents: ["橋本桃呼", "東山恵里沙", "松本ももな"],
  },
  {
    kind: "youtube",
    key: "vXR9vxPuTAo",
    title:
      "映画「事故物件ゾク 恐い間取り」ホラー映画界の名手・中田秀夫監督にホラー大好きアイドル・城月菜央（高嶺のなでしこ）がインタビュー👻",
    authorName: "ホラーちゃんねる",
    publishedAt: "2025-07-20",
    mediaUrl: "https://youtu.be/vXR9vxPuTAo",
    imageUrl: "https://i.ytimg.com/vi/vXR9vxPuTAo/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "g1t3ae5gsjc",
    title:
      "【4Kグラビア】【高嶺のなでしこ】が贈る忘れられない夏！最高のサマーチューン！！【メイキング】",
    authorName: "グラビアンエイジch【KADOKAWAドラゴンエイジ公式CH】",
    publishedAt: "2025-07-19",
    mediaUrl: "https://youtu.be/g1t3ae5gsjc",
    imageUrl: "https://i.ytimg.com/vi/g1t3ae5gsjc/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "橋本桃呼", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "Bbzh9bKvdiE",
    title:
      "【4Kグラビア】【高嶺のなでしこ】解禁された息をのむ美しさ…新たな魅力に心奪われる♡【メイキング】",
    authorName: "グラビアンエイジch【KADOKAWAドラゴンエイジ公式CH】",
    publishedAt: "2025-07-18",
    mediaUrl: "https://youtu.be/Bbzh9bKvdiE",
    imageUrl: "https://i.ytimg.com/vi/Bbzh9bKvdiE/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "橋本桃呼", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "dcIbmeMiwmE",
    title:
      "『TIF presents ONE SONG FES』の裏側へ！橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#5】",
    authorName: "Quick Japan",
    publishedAt: "2025-07-18",
    mediaUrl: "https://youtu.be/dcIbmeMiwmE",
    imageUrl: "https://i.ytimg.com/vi/dcIbmeMiwmE/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/761375",
    title: "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第2回『M3GAN』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2025-07-18",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/761375",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2025/07/761375_02.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "zPXVFUf2ZKw",
    title:
      "【4Kグラビア】【高嶺のなでしこ】と過ごすキラめく夏！弾ける笑顔は太陽より眩しい！【メイキング】",
    authorName: "グラビアンエイジch【KADOKAWAドラゴンエイジ公式CH】",
    publishedAt: "2025-07-10",
    mediaUrl: "https://youtu.be/zPXVFUf2ZKw",
    imageUrl: "https://i.ytimg.com/vi/zPXVFUf2ZKw/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "橋本桃呼", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://spice.eplus.jp/articles/338472",
    title:
      "高嶺のなでしこ　「メンバー全員がかわいくて、曲もめちゃくちゃ良いので、“この夏、好きになっちゃえばいいのに。”と心の底から思っています（笑）」 | SPICE - エンタメ特化型情報メディア スパイス",
    authorName: "SPICE（スパイス）｜エンタメ特化型情報メディア スパイス",
    publishedAt: "2025-07-10",
    mediaUrl: "https://spice.eplus.jp/articles/338472",
    imageUrl:
      "https://spice.eplus.jp/images/tkZ9WmwOHc24Gm54y0QBezx2Ko3q1GNf9u5WFMSFZCC7CSI5xBtg8nXarC90Gq4b",
    category: "article",
    presents: ["橋本桃呼", "東山恵里沙"],
  },
  {
    kind: "ogp",
    key: "https://fineboys-online.jp/interview/detail.php?id=5602",
    title:
      "この夏、高嶺のなでしこ沼に！5曲連続配信リリースで幕張へ！ | インタビュー | FINEBOYS Online",
    authorName: "FINEBOYS Online｜ファインボーイズオンライン",
    publishedAt: "2025-07-09",
    mediaUrl: "https://fineboys-online.jp/interview/detail.php?id=5602",
    imageUrl: "https://cdn.fineboys-online.jp/thegear/content/theme/img/org/article/5602/main.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.walkerplus.com/article/1275466/",
    title:
      "『高嶺のなでしこ』松本ももな「絶対に成功させて、みんなで最高の景色を見たいと思っています」｜ウォーカープラス",
    authorName: "ウォーカープラス（Walkerplus）",
    publishedAt: "2025-07-09",
    mediaUrl: "https://www.walkerplus.com/article/1275466/",
    imageUrl: "https://news.walkerplus.com/article/1275466/14864090_615.jpg",
    category: "article",
    presents: ["松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1276361/",
    title:
      "高嶺のなでしこメンバーおすすめ、5曲連続配信リリースと一緒に注目してほしい“好き曲”紹介 | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2025-07-09",
    mediaUrl: "https://thetv.jp/news/detail/1276361/",
    imageUrl: "https://thetv.jp/i/nw/1276361/14882183.jpg?w=1284",
    category: "article",
    presents: ["城月菜央", "橋本桃呼", "葉月紗蘭", "東山恵里沙", "星谷美来"],
  },
  {
    kind: "ogp",
    key: "https://asageimuse.com/excerpt/26662",
    title:
      "高嶺のなでしこ、9月の幕張ワンマンライブ＆5曲連続配信リリースへの想いを語る！【インタビュー前編】",
    authorName: "asageiMUSE",
    publishedAt: "2025-07-09",
    mediaUrl: "https://asageimuse.com/excerpt/26662",
    imageUrl:
      "https://asageimuse.com/wp-content/uploads/2025/07/a961abfe39e06c5c234c29d9e8e7cac9-1.jpg",
    category: "article",
    presents: [],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://asageimuse.com/excerpt/26675",
    title:
      "高嶺のなでしこ、映画出演やランウェイなど各メンバーの活躍ぶり＆好きなファッションを語る！【インタビュー後編】",
    authorName: "asageiMUSE",
    publishedAt: "2025-07-09",
    mediaUrl: "https://asageimuse.com/excerpt/26675",
    imageUrl:
      "https://asageimuse.com/wp-content/uploads/2025/07/2666ff8aaffe0b2dfa245cb9b33c7ea3-1.jpg",
    category: "article",
    presents: [],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://encount.press/archives/823787/",
    title:
      "高嶺のなでしこ、結成3年で着実に成長「スピード感を落とさずに」　幕張の先に目指す夢の舞台",
    authorName: "ENCOUNT",
    publishedAt: "2025-07-09",
    mediaUrl: "https://encount.press/archives/823787/",
    imageUrl:
      "https://encount.press/wp-content/uploads/2025/07/08234155/2d487b7e55e7564c2fb1e28c257e79a1.jpg",
    category: "article",
    presents: ["涼海すう", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://kaiwaiweb.com/news/11842/",
    title:
      "【超NATSUZOME2025ライブレポート】高嶺のなでしこ、夕映えのステージに響いた決意と可憐のダブルトーン - BEEEEM（ビーーーム）",
    authorName: "BEEEEM（ビーーーム）",
    publishedAt: "2025-07-09",
    mediaUrl: "https://kaiwaiweb.com/news/11842/",
    imageUrl:
      "https://kaiwaiweb.com/wp/wp-content/uploads/2025/07/takanenonadeshikosama_natsuzome_050-watermarked.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/71242/",
    title: "不破湊サンみたいなコーデがしたいっ♡「すぅにゃの推し活WORLD」 vol.4",
    authorName: "Popteen Media",
    publishedAt: "2025-07-08",
    mediaUrl: "https://popteen.co.jp/media/71242/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/06/bc543b038875365a3e0d076fda7dd39a.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1276360/",
    title:
      "高嶺のなでしこ、国民的アイドル目指して「凛とした日本女性の清楚な美しさを体現していきたい」 | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2025-07-08",
    mediaUrl: "https://thetv.jp/news/detail/1276360/",
    imageUrl: "https://thetv.jp/i/nw/1276360/14882149.jpg?w=1284",
    category: "article",
    presents: ["城月菜央", "橋本桃呼", "葉月紗蘭", "東山恵里沙", "星谷美来"],
  },
  {
    kind: "ogp",
    key: "https://rockinon.com/interview/detail/212621",
    title:
      "【インタビュー】かわいさもエモさも表現する10人組アイドル・高嶺のなでしこの魅力とは？ サウンドプロデューサー・HoneyWorksとの歩み、5ヶ月連続リリースで成長する今を語る－rockinon.com｜https://rockinon.com/interview/detail/212621",
    authorName: "rockinon.com",
    publishedAt: "2025-07-07",
    mediaUrl: "https://rockinon.com/interview/detail/212621",
    imageUrl: "https://rockinon.com/images/entry/width:1200/212621/1",
    category: "article",
    presents: ["橋本桃呼", "葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "ogp",
    key: "https://thetv.jp/news/detail/1276292/",
    title:
      "高嶺のなでしこ、初のドラマ エンディングテーマも入った5曲連続配信リリースから幕張ライブへ「成功できたら武道館に近づけるかも」 | WEBザテレビジョン",
    authorName: "WEBザテレビジョン",
    publishedAt: "2025-07-07",
    mediaUrl: "https://thetv.jp/news/detail/1276292/",
    imageUrl: "https://thetv.jp/i/nw/1276292/14881545.jpg?w=1284",
    category: "article",
    presents: ["涼海すう", "日向端ひな", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "Mk8RWBP3P2c",
    title:
      "“高嶺のなでしこ”レッスン中を突撃取材 海外公演映像・プライベート写真を大公開！(2025年7月5日)",
    authorName: "ANNnewsCH",
    publishedAt: "2025-07-05",
    mediaUrl: "https://youtu.be/Mk8RWBP3P2c",
    imageUrl: "https://i.ytimg.com/vi/Mk8RWBP3P2c/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "東山恵里沙", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://e.usen.com/interview/interview-original/takanenonadeshiko-kononatsu.html",
    title:
      "高嶺のなでしこ「この夏、好きになっちゃえばいいのに。」インタビュー――5曲連続配信リリースも第四弾！ | USENの音楽情報サイト「encore（アンコール）」",
    authorName: "USENの音楽情報サイト「encore（アンコール）」",
    publishedAt: "2025-07-05",
    mediaUrl: "https://e.usen.com/interview/interview-original/takanenonadeshiko-kononatsu.html",
    imageUrl: "https://e.usen.com/image/f0f709ba94639a734c63850a9eafefdf70432899.jpg",
    category: "article",
    presents: ["葉月紗蘭", "東山恵里沙", "日向端ひな"],
  },
  {
    kind: "ogp",
    key: "https://popnroll.tv/articles/43864",
    title:
      "🍭 高嶺のなでしこ［インタビュー］『LARME』とのタイアップで花開く“新しい可愛い”のカタチ「メンバーがモデルさんをしている姿って本当に尊い」 - Pop'n'Roll(ポップンロール)",
    authorName: "Pop'n'Roll",
    publishedAt: "2025-07-02",
    mediaUrl: "https://popnroll.tv/articles/43864",
    imageUrl:
      "https://img.popnroll.tv/uploads/news_item/og_image/43864/large_536A7886%E3%81%AE%E3%82%B3%E3%83%92%E3%82%9A%E3%83%BC.jpg",
    category: "article",
    presents: ["城月菜央", "橋本桃呼", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.oricon.co.jp/news/2393464/full/",
    title:
      "【インタビュー】高嶺のなでしこ、5曲連続配信リリース続行中　幕張メッセ単独ライブに向けた覚悟と決意 ",
    authorName: "オリコンニュース（ORICON NEWS）",
    publishedAt: "2025-07-02",
    mediaUrl: "https://www.oricon.co.jp/news/2393464/full/",
    imageUrl:
      "https://contents.oricon.co.jp/upimg/news/2394000/2393464/20250701_131838_p_o_16982842.jpg",
    category: "article",
    presents: ["涼海すう", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/73363/",
    title: "汗・風・湿気にもマケズ！前髪命JKの美バングキープ術",
    authorName: "Popteen Media",
    publishedAt: "2025-07-01",
    mediaUrl: "https://popteen.co.jp/media/73363/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/07/e92512132610dd098d357f2155bf891a.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://www.oricon.co.jp/special/71624/",
    title: "前髪、触角…日本独自のテクニックも　アイドルの前髪は、なぜ崩れない？ ",
    authorName: "オリコンニュース（ORICON NEWS）",
    publishedAt: "2025-06-30",
    mediaUrl: "https://www.oricon.co.jp/special/71624/",
    imageUrl:
      "https://contents.oricon.co.jp/special/img/71000/71624/social/img1200/1751248587411.jpg",
    category: "article",
    presents: ["松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://asageimuse.com/excerpt/26588",
    title:
      "高嶺のなでしこ、LARMEコラボのスペシャルファッションショーでランウェイをウォーキング！華麗な衣装と仕草で女性ファンを魅了",
    authorName: "asageiMUSE",
    publishedAt: "2025-06-28",
    mediaUrl: "https://asageimuse.com/excerpt/26588",
    imageUrl:
      "https://asageimuse.com/wp-content/uploads/2025/06/4588d32f3f4768553b9751f095d26419.jpg",
    category: "article",
    presents: [],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://encount.press/archives/815872/",
    title: "高嶺のなでしこ、大成功の中国2公演　想像を超えた現地ファンの熱気「愛をいっぱい感じた」",
    authorName: "ENCOUNT",
    publishedAt: "2025-06-24",
    mediaUrl: "https://encount.press/archives/815872/",
    imageUrl:
      "https://encount.press/wp-content/uploads/2025/06/23175423/51a082b50124c82d356ebd1e3f03c26d.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.sanspo.com/article/20250622-6HUUHVLQONISZL3HTM2GG2HM2A/",
    title:
      "高嶺のなでしこ、気合爆上がり中！　22日グループ初の中国・上海単独ライブへ籾山ひめり＆城月菜央＆涼海すうが意気込み",
    authorName: "サンスポ",
    publishedAt: "2025-06-22",
    mediaUrl: "https://www.sanspo.com/article/20250622-6HUUHVLQONISZL3HTM2GG2HM2A/",
    imageUrl:
      "https://www.sanspo.com/resizer/v2/KGZ3OTMTP5NS3AY3VSPLTB3WII.jpg?auth=1236eddc48027d0e6e679a68c5985ad456f834ceb8b38b059d6b2c1ffe96cea5&quality=50&focal=899%2C568&width=1200&height=630",
    category: "article",
    presents: ["涼海すう", "城月菜央", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://natalie.mu/music/pp/shutoko",
    title:
      "高嶺のなでしこが社会科見学！「日本橋川に青空を」首都高速道路日本橋区間地下化事業を学ぶ - 音楽ナタリー 特集・インタビュー",
    authorName: "音楽ナタリー",
    publishedAt: "2025-06-20",
    mediaUrl: "https://natalie.mu/music/pp/shutoko",
    imageUrl: "https://ogre.natalie.mu/media/pp/shutoko/shutoko_thumb.jpg?imwidth=1280&imdensity=1",
    category: "article",
    presents: ["城月菜央", "橋本桃呼", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.vanitymix.jp/music/takanenonadeshiko-5/",
    title: "高嶺のなでしこ VANITYMIX WEB LIMITED INTERVIEW",
    authorName: "VANITYMIX マガジン",
    publishedAt: "2025-06-18",
    mediaUrl: "https://www.vanitymix.jp/music/takanenonadeshiko-5/",
    imageUrl:
      "https://www.vanitymix.jp/wp-content/uploads/2025/06/ff63052e1a743c56968f2d857d1e5124-e1750209860562.jpg",
    category: "article",
    presents: ["葉月紗蘭", "東山恵里沙", "日向端ひな"],
  },
  {
    kind: "youtube",
    key: "LHigAd63pfM",
    title: "特別番組「ミルクにモ～夢中！」メイキング映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2025-06-13",
    mediaUrl: "https://youtu.be/LHigAd63pfM",
    imageUrl: "https://i.ytimg.com/vi/LHigAd63pfM/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://www.idol-culture.jp/geinou/175577/",
    title: "「高嶺のなでしこ」日向端ひな初主演映画クランクアップ｜BUBKA Web（ブブカ ウェブ）",
    authorName: "BUBKA Web（ブブカ ウェブ）",
    publishedAt: "2025-06-13",
    mediaUrl: "https://www.idol-culture.jp/geinou/175577/",
    imageUrl:
      "https://www.idol-culture.jp/wp-content/uploads/2025/06/7329ecbc7995b185409ce582518b1175-1.jpg",
    category: "article",
    presents: ["日向端ひな"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/756586",
    title: "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第1回『パラドクス』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2025-06-13",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/756586",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2025/05/756586_05.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/71575/",
    title: "体型コンプレックスをカバーする♡POPモデルの初夏コーデ《ガーリー編》",
    authorName: "Popteen Media",
    publishedAt: "2025-06-13",
    mediaUrl: "https://popteen.co.jp/media/71575/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/06/e4b0c1791ad46c4a718d7daa1fa15217.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://ameblo.jp/tetsu-and-tomo-tomo/entry-12909586509.html",
    title: "テツandトモ　トモ『矢口真里さん、籾山ひめりさん』",
    authorName: "テツandトモ　トモオフィシャルブログ「人生・毎日 ♪なんでだろう〜」Powered by Ameba",
    publishedAt: "2025-06-10",
    mediaUrl: "https://ameblo.jp/tetsu-and-tomo-tomo/entry-12909586509.html",
    imageUrl:
      "https://stat.ameba.jp/user_images/20250610/15/tetsu-and-tomo-tomo/cc/c4/j/o0810108015613892612.jpg",
    category: "article",
    presents: ["籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/71240/",
    title: "ルンルンになりきり！？推し概念コーデが超可愛い♡「すぅにゃの推し活WORLD」vol.3",
    authorName: "Popteen Media",
    publishedAt: "2025-06-10",
    mediaUrl: "https://popteen.co.jp/media/71240/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/06/556c59760770b4d88cef733f18789189.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "4QiodO_oM00",
    title:
      "【新作公開】『たっくーの震える怖い話』シーズン2配信開始！#たっくー #たっくーのふる怖 #怪談 #心霊",
    authorName: "タテドラ【公式】",
    publishedAt: "2025-06-05",
    mediaUrl: "https://youtu.be/4QiodO_oM00",
    imageUrl: "https://i.ytimg.com/vi/4QiodO_oM00/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "PvPKMtl6HQg",
    title: "【抜き打ち】モデルのカバンの中身チェック！後編【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2025-05-31",
    mediaUrl: "https://youtu.be/PvPKMtl6HQg",
    imageUrl: "https://i.ytimg.com/vi/PvPKMtl6HQg/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://www.cinemastyle.jp/horror/20094/",
    title: "高嶺のなでしこ・城月菜央さんが選ぶ2025年注目のホラー映画特集 | CinemaStyle",
    authorName: "CinemaStyle",
    publishedAt: "2025-05-23",
    mediaUrl: "https://www.cinemastyle.jp/horror/20094/",
    imageUrl:
      "https://www.cinemastyle.jp/wp-content/uploads/2025/05/takane-no-nadeshiko-horror.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "3SPYAYpyMbo",
    title: "【籾山ひめり編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-05-16",
    mediaUrl: "https://youtu.be/3SPYAYpyMbo",
    imageUrl: "https://i.ytimg.com/vi/3SPYAYpyMbo/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "hZw36eSapvY",
    title: "【松本ももな編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-05-14",
    mediaUrl: "https://youtu.be/hZw36eSapvY",
    imageUrl: "https://i.ytimg.com/vi/hZw36eSapvY/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな"],
  },
  {
    kind: "youtube",
    key: "4N2A7a9p_Bc",
    title: "【メイク動画】束感まつげメイクレシピ【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2025-05-14",
    mediaUrl: "https://youtu.be/4N2A7a9p_Bc",
    imageUrl: "https://i.ytimg.com/vi/4N2A7a9p_Bc/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/69203/",
    title:
      "現役アイドルの推し活仲間の作り方は？気になるお財布事情もチェック♡【すぅにゃの推し活WORLD Vol.2】",
    authorName: "Popteen Media",
    publishedAt: "2025-05-12",
    mediaUrl: "https://popteen.co.jp/media/69203/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/05/2.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://horror2.jp/72314",
    title:
      "シークエンスはやとも・Miyoshi・城月菜央（高嶺のなでしこ）インタビュー「霊って身近にたくさんいるものなんだ、という気付きを楽しんで」",
    authorName: "ホラー通信",
    publishedAt: "2025-05-12",
    mediaUrl: "https://horror2.jp/72314",
    imageUrl: "https://horror2.jp/files/2025/05/A7T00011f1.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "oXUZQ7MdEfA",
    title: "【踊ってみた】おとP誕生！？AIで即興で1曲作って踊ってみた！【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2025-05-10",
    mediaUrl: "https://youtu.be/oXUZQ7MdEfA",
    imageUrl: "https://i.ytimg.com/vi/oXUZQ7MdEfA/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "ViVWPLA3F0o",
    title: "【星谷美来編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-05-09",
    mediaUrl: "https://youtu.be/ViVWPLA3F0o",
    imageUrl: "https://i.ytimg.com/vi/ViVWPLA3F0o/hqdefault.jpg",
    category: "youtube",
    presents: ["星谷美来"],
  },
  {
    kind: "youtube",
    key: "d2Cl9Ls4HV4",
    title: "【日向端ひな編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-05-07",
    mediaUrl: "https://youtu.be/d2Cl9Ls4HV4",
    imageUrl: "https://i.ytimg.com/vi/d2Cl9Ls4HV4/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    key: "AYbP2wXl3K4",
    title: "【コーデ紹介】モデルたちのガチ私服！春のデニムコーデ大公開!!【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2025-05-05",
    mediaUrl: "https://youtu.be/AYbP2wXl3K4",
    imageUrl: "https://i.ytimg.com/vi/AYbP2wXl3K4/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://horror2.jp/72300",
    title:
      "ホラー好きアイドル　高嶺のなでしこ・城月菜央インタビュー「好きな作品と恐怖を感じるポイント」「憧れの伊藤潤二先生」",
    authorName: "ホラー通信",
    publishedAt: "2025-05-03",
    mediaUrl: "https://horror2.jp/72300",
    imageUrl: "https://horror2.jp/files/2025/05/A7T00253f1.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "mZEa6T8OZMA",
    title: "【東山恵里沙編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-05-02",
    mediaUrl: "https://youtu.be/mZEa6T8OZMA",
    imageUrl: "https://i.ytimg.com/vi/mZEa6T8OZMA/hqdefault.jpg",
    category: "youtube",
    presents: ["東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "qFp1I2tSi1o",
    title: "高嶺のなでしこ、新曲「メランコリックハニー」と過去最大規模の単独ライブ紹介映像を公開！",
    authorName: "WowKorea FAN",
    publishedAt: "2025-05-01",
    mediaUrl: "https://youtu.be/qFp1I2tSi1o",
    imageUrl: "https://i.ytimg.com/vi/qFp1I2tSi1o/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "xSME23C4vKA",
    title: "【春野莉々編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-30",
    mediaUrl: "https://youtu.be/xSME23C4vKA",
    imageUrl: "https://i.ytimg.com/vi/xSME23C4vKA/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々"],
    deleted: true,
  },
  {
    kind: "youtube",
    key: "0OcDmwQdoqg",
    title: 'TIF de Debut 2025 COMMENT MOVIE "高嶺のなでしこ"',
    authorName: "TIF de Debut 2025",
    publishedAt: "2025-04-28",
    mediaUrl: "https://youtu.be/0OcDmwQdoqg",
    imageUrl: "https://i.ytimg.com/vi/0OcDmwQdoqg/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/67181/",
    title: "【TikTok】アイドルユニット誕生？AIで作った『POPFUL』を初披露♡",
    authorName: "Popteen Media",
    publishedAt: "2025-04-28",
    mediaUrl: "https://popteen.co.jp/media/67181/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/04/35.02-0214b.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "x27ckzs7QM8",
    title:
      "【鈴木愛理が完コピダンス】「可愛くてごめん」by高嶺のなでしこ30分で本気習得!!＜固定カメラVer.＞【でしょでしょ‼】",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2025-04-26",
    mediaUrl: "https://youtu.be/x27ckzs7QM8",
    imageUrl: "https://i.ytimg.com/vi/x27ckzs7QM8/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "O-YUVzuHzas",
    title:
      "【鈴木愛理が完コピダンス】「可愛くてごめん」by高嶺のなでしこ30分で本気習得!!＜カメラが動くVer.＞【でしょでしょ‼】",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2025-04-26",
    mediaUrl: "https://youtu.be/O-YUVzuHzas",
    imageUrl: "https://i.ytimg.com/vi/O-YUVzuHzas/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "iOqKe2dx1LE",
    title: "【葉月紗蘭編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-25",
    mediaUrl: "https://youtu.be/iOqKe2dx1LE",
    imageUrl: "https://i.ytimg.com/vi/iOqKe2dx1LE/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "tqokE_2JmMg",
    title: "【橋本桃呼編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-23",
    mediaUrl: "https://youtu.be/tqokE_2JmMg",
    imageUrl: "https://i.ytimg.com/vi/tqokE_2JmMg/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "0Y8UVokoj3Y",
    title: "【高嶺のなでしこ】ホールツアー名古屋公演に向けてコメント到着！",
    authorName: "SUNDAY FOLK PROMOTION",
    publishedAt: "2025-04-22",
    mediaUrl: "https://youtu.be/0Y8UVokoj3Y",
    imageUrl: "https://i.ytimg.com/vi/0Y8UVokoj3Y/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "K_IuWutpyyE",
    title:
      "高嶺のなでしこ・籾山ひめり&日向端ひな、ランウェイ出演でファッションポイントを明かす！十代の頃の思い出も赤裸々告白　『超十代2025』独占インタビュー",
    authorName: "oricon",
    publishedAt: "2025-04-22",
    mediaUrl: "https://youtu.be/K_IuWutpyyE",
    imageUrl: "https://i.ytimg.com/vi/K_IuWutpyyE/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.oricon.co.jp/news/2380978/full/",
    title:
      "高嶺のなでしこ・籾山ひめり、ティーン世代に金言「やっておきたいなっていう思い出は全部叶えた方がいい」　日向端ひなが“十代の思い出”明かす「今思うと勉強しなって感じなんですけど(笑)」【インタビュー】 ",
    authorName: "オリコンニュース（ORICON NEWS）",
    publishedAt: "2025-04-22",
    mediaUrl: "https://www.oricon.co.jp/news/2380978/full/",
    imageUrl:
      "https://contents.oricon.co.jp/upimg/news/2381000/2380978/20250422_161105_p_o_94356142.jpg",
    category: "article",
    presents: ["日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://abema.tv/video/episode/90-979_s1_p310",
    title:
      "#310：美女13人がノブを翻弄！よく寝てなかったら死んでたSP - チャンスの時間 - シーズン (バラエティ) | 無料動画・見逃し配信を見るなら | ABEMA",
    authorName: "ABEMA",
    publishedAt: "2025-04-20",
    mediaUrl: "https://abema.tv/video/episode/90-979_s1_p310",
    imageUrl:
      "https://image.p-c2-x.abema-tv.com/image/programs/90-979_s1_p310/thumb002.png?height=720&quality=75&version=1769572818&width=1280",
    category: "video",
    presents: ["日向端ひな"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/66952/",
    title: "【新連載】すぅにゃの推し活WORLD〜vol.1 「イチバン好きなのは魔界ノりりむチャン♡」",
    authorName: "Popteen Media",
    publishedAt: "2025-04-20",
    mediaUrl: "https://popteen.co.jp/media/66952/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/04/42a5088ec45b9b100b6da6f37d8328ed.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "1004tylNRQ8",
    title:
      "【アイドルの本気】鈴木愛理が高嶺のなでしこと「可愛くてごめん」ダンスレッスン！「ざまあ顔」披露で大盛り上がり！バラエティで滑った時の可愛い挽回方法は？【でしょでしょ‼︎】",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2025-04-19",
    mediaUrl: "https://youtu.be/1004tylNRQ8",
    imageUrl: "https://i.ytimg.com/vi/1004tylNRQ8/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "oVCvpyCwM3k",
    title: "【涼海すう編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-18",
    mediaUrl: "https://youtu.be/oVCvpyCwM3k",
    imageUrl: "https://i.ytimg.com/vi/oVCvpyCwM3k/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "5OZY2qzgoCc",
    title:
      "いざ、ワンマンライブへ！ 橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#4】",
    authorName: "Quick Japan",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/5OZY2qzgoCc",
    imageUrl: "https://i.ytimg.com/vi/5OZY2qzgoCc/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "IO4heh_HROY",
    title:
      "【高嶺のなでしこ】夏休みの合宿免許は運転免許トロッカ！で決まり★│人気につき予約へお早めにー！",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/IO4heh_HROY",
    imageUrl: "https://i.ytimg.com/vi/IO4heh_HROY/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "FBD8_in-9oU",
    title: "【城月菜央編】たかねこドライブ格言｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/FBD8_in-9oU",
    imageUrl: "https://i.ytimg.com/vi/FBD8_in-9oU/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "UIuRvdpud80",
    title:
      "【未公開映像】プロバスケ選手アイドルフェス出演1日密着！初出し裏側映像から大盛り上がりの本番ステージまでカメラが潜入しました【ロウルとアイドルフェス】",
    authorName: "川崎ブレイブサンダース",
    publishedAt: "2025-04-11",
    mediaUrl: "https://youtu.be/UIuRvdpud80",
    imageUrl: "https://i.ytimg.com/vi/UIuRvdpud80/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/65848/",
    title: "春はトレンドのミニスカデニムで愛されガールに♡【私服デニムSNAP③】",
    authorName: "Popteen Media",
    publishedAt: "2025-04-09",
    mediaUrl: "https://popteen.co.jp/media/65848/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/03/1-3.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/65391/",
    title: "モデル別♡韓国コスメ推しリップLIST",
    authorName: "Popteen Media",
    publishedAt: "2025-04-08",
    mediaUrl: "https://popteen.co.jp/media/65391/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/04/88bf539d49dcf477eadfe7d2def7b04a.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/66054/",
    title: "すぅにゃ、りんりん、せらぴーの束感まつげメイクレシピ",
    authorName: "Popteen Media",
    publishedAt: "2025-04-01",
    mediaUrl: "https://popteen.co.jp/media/66054/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/03/8708a4dcd621422ef95c489d5622fade-e1743394901211.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://natalie.mu/music/pp/churaku-takaneko02",
    title:
      "高嶺のなでしこ×酪農応援プロジェクト特集｜牛乳が酪農家から店頭に届くまでを描いた「ミルクの旅路」 - 音楽ナタリー 特集・インタビュー",
    authorName: "音楽ナタリー",
    publishedAt: "2025-03-28",
    mediaUrl: "https://natalie.mu/music/pp/churaku-takaneko02",
    imageUrl:
      "https://ogre.natalie.mu/media/pp/churaku-takaneko02/churaku-takaneko02_ogp2.jpg?imwidth=1280&imdensity=1",
    category: "article",
    presents: ["涼海すう", "葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "VVa7yYcWNFs",
    title:
      "【ラパルフェ＆高嶺のなでしこ】コロッケリスペクトコンビ(？)とVIVANT名コンビ(？)がクイズに挑戦！　#クイズ5GATES",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2025-03-24",
    mediaUrl: "https://youtu.be/VVa7yYcWNFs",
    imageUrl: "https://i.ytimg.com/vi/VVa7yYcWNFs/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "Tfc3b3CMao4",
    title:
      "たかねこ・松本ももなは「おりぼんの擬人化」一番オシャレなメンバーは？【IDOL RUNWAY COLLECTION 2025 Supported by TGC】",
    authorName: "【entax】編集部🪄",
    publishedAt: "2025-03-21",
    mediaUrl: "https://youtu.be/Tfc3b3CMao4",
    imageUrl: "https://i.ytimg.com/vi/Tfc3b3CMao4/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "X7uPByzLhSY",
    title:
      "【保育されちゃうアイドル!?】城月 菜央の保育士1日体験に密着【高嶺のなでしこ】【HoneyWorks】",
    authorName: "保育士バンク！チャンネル【公式】",
    publishedAt: "2025-03-21",
    mediaUrl: "https://youtu.be/X7uPByzLhSY",
    imageUrl: "https://i.ytimg.com/vi/X7uPByzLhSY/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://www.entax.news/post/202503211900.html",
    title:
      "高嶺のなでしこ、ランウェイ挑戦！橋本桃呼「本人は“おりぼんの擬人化”って自分のことを言っているんですけど…」|entax（エンタックス）",
    authorName: "entax（エンタックス）",
    publishedAt: "2025-03-21",
    mediaUrl: "https://www.entax.news/post/202503211900.html",
    imageUrl: "https://www.entax.news/wp-content/uploads/2025/03/1_4Z1A8800.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "ep3Z2kpyfmQ",
    title:
      "「アイドルの責任」橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#3】",
    authorName: "Quick Japan",
    publishedAt: "2025-03-14",
    mediaUrl: "https://youtu.be/ep3Z2kpyfmQ",
    imageUrl: "https://i.ytimg.com/vi/ep3Z2kpyfmQ/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "kNXz-Ai5lGA",
    title: "【高嶺のなでしこ】運転免許トロッカクイズ 第5問！(星谷美来×城月菜央)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-03-07",
    mediaUrl: "https://youtu.be/kNXz-Ai5lGA",
    imageUrl: "https://i.ytimg.com/vi/kNXz-Ai5lGA/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "星谷美来"],
  },
  {
    kind: "youtube",
    key: "EnGLaMDVNy4",
    title: "ミルクの旅路　ダイジェスト版",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2025-03-06",
    mediaUrl: "https://youtu.be/EnGLaMDVNy4",
    imageUrl: "https://i.ytimg.com/vi/EnGLaMDVNy4/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "7m9f8omnNoM",
    title: "ミルクの旅路",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2025-03-06",
    mediaUrl: "https://youtu.be/7m9f8omnNoM",
    imageUrl: "https://i.ytimg.com/vi/7m9f8omnNoM/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "葉月紗蘭", "東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "_19fXNWKm9A",
    title:
      "５時に夢中！スピンオフ特番 ミルクにモ～夢中！　TOKYO MX×ウェザーニュース×高嶺のなでしこ",
    authorName: "ウェザーニュース",
    publishedAt: "2025-03-06",
    mediaUrl: "https://youtu.be/_19fXNWKm9A",
    imageUrl: "https://i.ytimg.com/vi/_19fXNWKm9A/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "_qposQVQviw",
    title:
      "「もっと自分を好きになりたい」橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる#2】",
    authorName: "Quick Japan",
    publishedAt: "2025-02-20",
    mediaUrl: "https://youtu.be/_qposQVQviw",
    imageUrl: "https://i.ytimg.com/vi/_qposQVQviw/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "ftfQlE6dGxQ",
    title:
      "【高嶺のなでしこ】運転免許トロッカクイズ 第4問！(葉月紗蘭×日向端ひな)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-02-19",
    mediaUrl: "https://youtu.be/ftfQlE6dGxQ",
    imageUrl: "https://i.ytimg.com/vi/ftfQlE6dGxQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭", "日向端ひな"],
  },
  {
    kind: "youtube",
    key: "RG7S6MunsWo",
    title: "【ドラマ】「信じてたのに!!」親友に家族を壊された。",
    authorName: "CUL DRAMA / カルドラマ",
    publishedAt: "2025-02-15",
    mediaUrl: "https://youtu.be/RG7S6MunsWo",
    imageUrl: "https://i.ytimg.com/vi/RG7S6MunsWo/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々"],
  },
  {
    kind: "youtube",
    key: "UDB1pOUgmYA",
    title:
      "【高嶺のなでしこ】運転免許トロッカクイズ 第3問！(東山恵里沙×春野莉々)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-02-12",
    mediaUrl: "https://youtu.be/UDB1pOUgmYA",
    imageUrl: "https://i.ytimg.com/vi/UDB1pOUgmYA/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々", "東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "kdXGcSF4xvI",
    title: "♡日向端ひなちゃん×Ank Rougeカタログメイキング♡",
    authorName: "Ank Rouge channel♡",
    publishedAt: "2025-02-06",
    mediaUrl: "https://youtu.be/kdXGcSF4xvI",
    imageUrl: "https://i.ytimg.com/vi/kdXGcSF4xvI/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな"],
    deleted: true,
  },
  {
    kind: "youtube",
    key: "JV_sPRXFHBA",
    title:
      "「アイドル、向いてないかも」橋本桃呼（高嶺のなでしこ）密着ドキュメント【もういちど、アイドルを生きる #1】",
    authorName: "Quick Japan",
    publishedAt: "2025-02-05",
    mediaUrl: "https://youtu.be/JV_sPRXFHBA",
    imageUrl: "https://i.ytimg.com/vi/JV_sPRXFHBA/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "static",
    key: "https://outofmusic.net/?p=1540",
    title:
      "②【先行掲載・WEBオリジナル記事】国立代々木第二体育館公演開催！！高嶺のなでしこ。総1万6,000字 ロング・インタビュー 前編、先行掲載！②",
    authorName: "OUT of MUSIC",
    publishedAt: "2025-02-04",
    mediaUrl: "https://outofmusic.net/?p=1540",
    imageUrl: "/media/2025/2025-02-04_OUT of MUSIC.webp",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "oOOs4VLYs_I",
    title:
      "【高嶺のなでしこ】運転免許トロッカクイズ 第2問！(籾山ひめり×松本ももな)｜運転免許トロッカ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-02-03",
    mediaUrl: "https://youtu.be/oOOs4VLYs_I",
    imageUrl: "https://i.ytimg.com/vi/oOOs4VLYs_I/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "cEUL8pCvSdA",
    title: "私たちの本当の思いを伝えます【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2025-02-01",
    mediaUrl: "https://youtu.be/cEUL8pCvSdA",
    imageUrl: "https://i.ytimg.com/vi/cEUL8pCvSdA/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/61981/",
    title: "束感まつ毛命のアイドルJK、『高嶺のなでしこ』のすぅにゃ",
    authorName: "Popteen Media",
    publishedAt: "2025-02-01",
    mediaUrl: "https://popteen.co.jp/media/61981/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/01/IMG_6469-e1738333842436.jpeg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "static",
    key: "https://fod.fujitv.co.jp/title/2c78/2c78120058/",
    title: "有野屋書店 第32回 ゲスト 高嶺のなでしこ 日向端ひな・涼海すう",
    authorName: "FODプレミアム",
    publishedAt: "2025-01-31",
    mediaUrl: "https://fod.fujitv.co.jp/title/2c78/2c78120058/",
    imageUrl: "/media/2025/2025-01-31_有野屋書店.webp",
    category: "video",
    presents: ["涼海すう", "日向端ひな"],
  },
  {
    kind: "ogp",
    key: "https://popnroll.tv/articles/42189",
    title:
      "🍭 【連載】高嶺のなでしこ 東山恵里沙「アイドルからしか得られない栄養素」vol.1：AVAM「幸福度の高いライブでした」 - Pop'n'Roll(ポップンロール)",
    authorName: "Pop'n'Roll",
    publishedAt: "2025-01-27",
    mediaUrl: "https://popnroll.tv/articles/42189",
    imageUrl:
      "https://img.popnroll.tv/uploads/news_item/image/42189/large__%E9%9B%86%E5%90%88_.jpeg",
    category: "article",
    presents: ["東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "eSlN7odHbMY",
    title: "【高嶺のなでしこ】夏休みは運転免許トロッカ！で合宿免許に行こう♪│ご予約はお早めに☆",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-01-22",
    mediaUrl: "https://youtu.be/eSlN7odHbMY",
    imageUrl: "https://i.ytimg.com/vi/eSlN7odHbMY/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "ItE-wU39oVg",
    title:
      "【高嶺のなでしこ】大人気の春休みシーズン★運転免許トロッカ！で免許をGETしよう！│ご予約へ急げー！",
    authorName: "運転免許トロッカ!",
    publishedAt: "2025-01-22",
    mediaUrl: "https://youtu.be/ItE-wU39oVg",
    imageUrl: "https://i.ytimg.com/vi/ItE-wU39oVg/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "aKTCaOrm3F4",
    title: "【柚姫の部屋】新春スペシャル2025 第2部！",
    authorName: "TEAM SHACHI【公式】",
    publishedAt: "2025-01-13",
    mediaUrl: "https://youtu.be/aKTCaOrm3F4",
    imageUrl: "https://i.ytimg.com/vi/aKTCaOrm3F4/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "橋本桃呼", "東山恵里沙"],
  },
  {
    kind: "ogp",
    key: "https://teamshachi.nagoya/contents/883149",
    title: "YouTube「柚姫の部屋」新春12時間スペシャル生配信！",
    authorName: "TEAM SHACHI オフィシャルサイト",
    publishedAt: "2025-01-13",
    mediaUrl: "https://teamshachi.nagoya/contents/883149",
    imageUrl:
      "https://teamshachi.nagoya/s3/skiyaki/uploads/ckeditor/pictures/687086/content_%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88_2025-01-10_19.16.56.png",
    category: "video",
    presents: ["城月菜央", "橋本桃呼", "東山恵里沙"],
    deleted: true,
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/58588/",
    title: "なんでもRANKING スクール部門!",
    authorName: "Popteen Media",
    publishedAt: "2025-01-01",
    mediaUrl: "https://popteen.co.jp/media/58588/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/01/popranking_schoolICa-1.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/59103/",
    title: "POPモ・クリモの勝手に妄想イメージRANKING！",
    authorName: "Popteen Media",
    publishedAt: "2025-01-01",
    mediaUrl: "https://popteen.co.jp/media/59103/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/01/IMG_5007.jpeg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/55859/",
    title: "SNAP！POPモ19人のクリスマスコーデを一挙ご紹介♡",
    authorName: "Popteen Media",
    publishedAt: "2025-12-24",
    mediaUrl: "https://popteen.co.jp/media/55859/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/12/IMG_3517.jpeg",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/57339/",
    title: "POPモクリスマスSNAPコーデ♡〜ちょいROCK界隈編〜",
    authorName: "Popteen Media",
    publishedAt: "2025-12-12",
    mediaUrl: "https://popteen.co.jp/media/57339/",
    imageUrl: "https://popteen.co.jp/media/wp-content/uploads/sites/2/2024/12/33-2.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
];
