import { RandomGoods, TradeTextType } from "~/features/products/product";

export const たかねこフェスvol4_目印チャーム: RandomGoods = {
  id: "ランダム目印チャーム「たかねこフェス vol.4」",
  slug: "目印チャーム「たかねこフェス vol.4」",
  name: "ランダム目印チャーム「たかねこフェス vol.4」ver.",
  year: 2025,
  series: "たかねこフェス vol.4",
  category: "目印チャーム",
  tradeText: TradeTextType.NameOnly,
  url: "/takaneko/goods/2025/2025-04-06_目印チャーム「たかねこフェス vol.4」.webp",
  width: 428,
  height: 218,
  lineup: [
    { id: 1, name: "城月菜央", description: "" },
    { id: 2, name: "涼海すう", description: "" },
    { id: 3, name: "橋本桃呼", description: "" },
    { id: 4, name: "葉月紗蘭", description: "" },
    { id: 5, name: "春野莉々", description: "" },
    { id: 6, name: "東山恵里沙", description: "" },
    { id: 7, name: "日向端ひな", description: "" },
    { id: 8, name: "星谷美来", description: "" },
    { id: 9, name: "松本ももな", description: "" },
    { id: 10, name: "籾山ひめり", description: "" },
  ],
  withFrame: true,
  positions: [
    { id: 1, x: 41, y: 58, width: 44, height: 44 },
    { id: 2, x: 111, y: 58, width: 44, height: 44 },
    { id: 3, x: 181, y: 54, width: 44, height: 44 },
    { id: 4, x: 266, y: 58, width: 44, height: 44 },
    { id: 5, x: 350, y: 58, width: 44, height: 44 },
    { id: 6, x: 40, y: 145, width: 44, height: 44 },
    { id: 7, x: 113, y: 145, width: 44, height: 44 },
    { id: 8, x: 187, y: 143, width: 44, height: 44 },
    { id: 9, x: 268, y: 145, width: 44, height: 44 },
    { id: 10, x: 348, y: 139, width: 44, height: 44 },
  ],
};
