import { RandomGoods, TradeTextType } from "~/features/products/product";

export const メンバー個別メッセージ継続特典バレンタインデザイン_ミニフォト: RandomGoods = {
  id: "メンバー個別メッセージ継続特典バレンタイン デザイン ミニフォトカード",
  slug: "ミニフォトカード「メンバー個別メッセージ継続特典バレンタイン デザイン」",
  name: "ミニフォトカード「メンバー個別メッセージ継続特典バレンタイン デザイン」",
  year: 2025,
  series: "メンバー個別メッセージ継続特典バレンタイン デザイン",
  category: "ミニフォト",
  tradeText: TradeTextType.NameOnly,
  url: "/takaneko/goods/2025/2025-02-14_ミニフォトカード「メンバー個別メッセージ継続特典バレンタインデザイン」.png",
  width: 1086,
  height: 679,
  lineup: [
    { id: 1, name: "城月菜央", description: "" },
    { id: 2, name: "涼海すう", description: "" },
    { id: 3, name: "橋本桃呼", description: "" },
    { id: 4, name: "葉月紗蘭", description: "" },
    { id: 5, name: "春野莉々", description: "" },
    { id: 6, name: "東山恵里沙", description: "" },
    { id: 7, name: "日向端ひな", description: "" },
    { id: 8, name: "星谷美来", description: "" },
    { id: 9, name: "松本ももな", description: "" },
    { id: 10, name: "籾山ひめり", description: "" },
  ],
  withFrame: false,
  positions: [
    { id: 1, x: 11, y: 10, width: 203, height: 324 },
    { id: 2, x: 225, y: 10, width: 203, height: 324 },
    { id: 3, x: 439, y: 10, width: 203, height: 324 },
    { id: 4, x: 653, y: 10, width: 203, height: 324 },
    { id: 5, x: 867, y: 10, width: 203, height: 324 },
    { id: 6, x: 11, y: 342, width: 203, height: 324 },
    { id: 7, x: 225, y: 342, width: 203, height: 324 },
    { id: 8, x: 439, y: 342, width: 203, height: 324 },
    { id: 9, x: 653, y: 342, width: 203, height: 324 },
    { id: 10, x: 867, y: 342, width: 203, height: 324 },
  ],
};
