import { RandomGoods, TradeTextType } from "~/features/products/product";

export const AWonderfulEncounter_にゃでしこステッカー: RandomGoods = {
  id: "ランダムにゃでしこドットステッカー",
  slug: "ランダムにゃでしこドットステッカー",
  name: "ランダムにゃでしこドットステッカー",
  year: 2025,
  series: "A Wonderful Encounter",
  category: "ステッカー",
  tradeText: TradeTextType.NameOnly,
  url: "/takaneko/goods/2025/2025-09-07_ランダムにゃでしこドットステッカー.webp",
  width: 323,
  height: 183,
  lineup: [
    { id: 1, name: "ルニャ・コーチ", description: "" },
    { id: 2, name: "すうにゃろう", description: "" },
    { id: 3, name: "はしもと もふ呼", description: "" },
    { id: 4, name: "らあら", description: "" },
    { id: 5, name: "にゃーさ", description: "" },
    { id: 6, name: "たま", description: "" },
    { id: 7, name: "ちゃーみー", description: "" },
    { id: 8, name: "ぽにゃん🎀", description: "" },
    { id: 9, name: "もみさん。", description: "" },
    { id: 9, name: "てんにゃ", description: "" },
  ],
  withFrame: true,
  positions: [
    { id: 1, x: 16, y: 16, width: 53, height: 68 },
    { id: 2, x: 75, y: 16, width: 53, height: 68 },
    { id: 3, x: 135, y: 16, width: 53, height: 68 },
    { id: 4, x: 194, y: 16, width: 53, height: 68 },
    { id: 5, x: 254, y: 16, width: 53, height: 68 },
    { id: 6, x: 16, y: 100, width: 53, height: 68 },
    { id: 7, x: 75, y: 100, width: 53, height: 68 },
    { id: 8, x: 135, y: 100, width: 53, height: 68 },
    { id: 9, x: 194, y: 100, width: 53, height: 68 },
    { id: 10, x: 254, y: 100, width: 53, height: 68 },
  ],
};
