import { RandomGoods } from "~/features/products/product";

export const ラブレターカード: RandomGoods = {
  id: "ラブレターカード",
  slug: "ラブレターカード",
  name: "ランダムラブレターカード",
  year: 2025,
  series: "Cute for life",
  category: "ラブレターカード",
  url: "/takaneko/goods/2025/2025-02-14_ラブレターカード.webp",
  width: 430,
  height: 162,
  lineup: [
    { id: 1, name: "城月菜央", description: "" },
    { id: 2, name: "涼海すう", description: "" },
    { id: 3, name: "橋本桃呼", description: "" },
    { id: 4, name: "葉月紗蘭", description: "" },
    { id: 5, name: "春野莉々", description: "" },
    { id: 6, name: "東山恵里沙", description: "" },
    { id: 7, name: "日向端ひな", description: "" },
    { id: 8, name: "星谷美来", description: "" },
    { id: 9, name: "松本ももな", description: "" },
    { id: 10, name: "籾山ひめり", description: "" },
  ],
  positions: [
    { id: 1, x: 178, y: 11, width: 43, height: 67 },
    { id: 2, x: 227, y: 11, width: 43, height: 67 },
    { id: 3, x: 277, y: 11, width: 43, height: 67 },
    { id: 4, x: 327, y: 11, width: 43, height: 67 },
    { id: 5, x: 377, y: 11, width: 43, height: 67 },
    { id: 6, x: 178, y: 85, width: 43, height: 67 },
    { id: 7, x: 227, y: 85, width: 43, height: 67 },
    { id: 8, x: 277, y: 85, width: 43, height: 67 },
    { id: 9, x: 327, y: 85, width: 43, height: 67 },
    { id: 10, x: 377, y: 85, width: 43, height: 67 },
  ],
};
