import { RandomGoods, TradeTextType } from "~/features/products/product";

export const SpringRide_缶バッジ: RandomGoods = {
  id: "ランダム缶バッジ「Spring Ride」",
  slug: "缶バッジ「Spring Ride」",
  name: "ランダム缶バッジ「Spring Ride」ver.",
  year: 2025,
  series: "Spring Ride",
  category: "缶バッジ",
  tradeText: TradeTextType.NameOnly,
  url: "/takaneko/goods/2025/2025-05-06_缶バッジ「Spring Ride」.webp",
  width: 448,
  height: 211,
  lineup: [
    { id: 1, name: "城月菜央", description: "" },
    { id: 2, name: "涼海すう", description: "" },
    { id: 3, name: "橋本桃呼", description: "" },
    { id: 4, name: "葉月紗蘭", description: "" },
    { id: 5, name: "春野莉々", description: "" },
    { id: 6, name: "東山恵里沙", description: "" },
    { id: 7, name: "日向端ひな", description: "" },
    { id: 8, name: "星谷美来", description: "" },
    { id: 9, name: "松本ももな", description: "" },
    { id: 10, name: "籾山ひめり", description: "" },
  ],
  withFrame: true,
  positions: [
    { id: 1, x: 12, y: 19, width: 81, height: 81 },
    { id: 2, x: 96, y: 19, width: 81, height: 81 },
    { id: 3, x: 179, y: 19, width: 81, height: 81 },
    { id: 4, x: 262, y: 19, width: 81, height: 81 },
    { id: 5, x: 345, y: 19, width: 81, height: 81 },
    { id: 6, x: 12, y: 112, width: 81, height: 81 },
    { id: 7, x: 96, y: 112, width: 81, height: 81 },
    { id: 8, x: 179, y: 112, width: 81, height: 81 },
    { id: 9, x: 262, y: 112, width: 81, height: 81 },
    { id: 10, x: 345, y: 112, width: 81, height: 81 },
  ],
};
