import { MediaDetails } from "~/features/media/types";

export const metadata2023: MediaDetails[] = [
  {
    kind: "youtube",
    title:
      "【高嶺のなでしこ】秘蔵！ヘアメイク中のももなんを直撃｜撮影バッグステージvol.1（松本ももな）",
    authorName: "運転免許トロッカ!",
    publishedAt: "2023-11-29",
    mediaUrl: "https://youtu.be/iZfWABjcVUM",
    imageUrl: "https://i.ytimg.com/vi/iZfWABjcVUM/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな"],
  },
  {
    kind: "youtube",
    title:
      "【ドS鈴木愛理】大バズり中の苦労人アイドル「高嶺のなでしこ」を追い詰めたらオーイシ爆笑！辛い時に救われたアニメキャラの名言とは!?【アニソン神曲カバーでしょdeショー‼】",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2023-11-18",
    mediaUrl: "https://youtu.be/uYGUgxcG9R0",
    imageUrl: "https://i.ytimg.com/vi/uYGUgxcG9R0/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼", "日向端ひな", "松本ももな"],
  },
  {
    kind: "youtube",
    title: '高嶺のなでしこ がPR！春休みの合宿免許のご予約は"運転免許トロッカ！"',
    authorName: "運転免許トロッカ!",
    publishedAt: "2023-11-06",
    mediaUrl: "https://youtu.be/-aUWpjcSgKY",
    imageUrl: "https://i.ytimg.com/vi/-aUWpjcSgKY/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title: "【飲まなくてごめん】酪農応援アンバサダー「高嶺のなでしこ」が牧場で、酪農体験に挑戦！",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2023-10-16",
    mediaUrl: "https://youtu.be/RbrtKRtNMpY",
    imageUrl: "https://i.ytimg.com/vi/RbrtKRtNMpY/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    title: '"高嶺のなでしこ"が「運転免許トロッカ！ゲーム」で白熱のバトル！(後編)',
    authorName: "運転免許トロッカ!",
    publishedAt: "2023-10-12",
    mediaUrl: "https://youtu.be/rPueVet2x70",
    imageUrl: "https://i.ytimg.com/vi/rPueVet2x70/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼", "春野莉々", "東山恵里沙", "日向端ひな"],
  },
  {
    kind: "youtube",
    title: "高嶺のなでしこ、新曲発表の感想と1周年記念ライブを終えた感想インタビュー実施！",
    authorName: "wowKorea FAN",
    publishedAt: "2023-09-19",
    mediaUrl: "https://youtu.be/dcE73pJT4rA",
    imageUrl: "https://i.ytimg.com/vi/dcE73pJT4rA/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    title:
      "【インタビュー】高嶺のなでしこ・松本ももな、星谷美来、東山恵里沙が『すきっちゅーの！』MVの可愛さを語る！,【インタビュー】高嶺のなでしこ・松本ももな、星谷美来、東山恵里沙が『すきっちゅーの！』MVの可愛さを語る！ | WWSチャンネル",
    authorName:
      "WWSチャンネル,WWSチャンネル | ファッション・音楽・アイドルの総合情報サイト　無料ネット動画＆写真芸能ニュース",
    publishedAt: "2023-09-06",
    mediaUrl: "https://www.wws-channel.com/girls2/450073.html",
    imageUrl: "https://www.wws-channel.com/wp-content/uploads/2023/09/00_1-13.jpg",
    category: "article",
    presents: ["東山恵里沙", "星谷美来", "松本ももな"],
  },
  {
    kind: "youtube",
    title: "星乃夢奈『今好きになる。』Official Music Video",
    authorName: "ゆなちゃんねる",
    publishedAt: "2023-08-31",
    mediaUrl: "https://youtu.be/SZIHQHnKJIc",
    imageUrl: "https://i.ytimg.com/vi/SZIHQHnKJIc/hqdefault.jpg",
    category: "youtube",
    presents: ["春野莉々"],
  },
  {
    kind: "youtube",
    title: '"高嶺のなでしこ"が「運転免許トロッカ！ゲーム」で白熱のバトル！(前編)',
    authorName: "運転免許トロッカ!",
    publishedAt: "2023-08-25",
    mediaUrl: "https://youtu.be/hNF9mhoS8jU",
    imageUrl: "https://i.ytimg.com/vi/hNF9mhoS8jU/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "葉月紗蘭", "星谷美来", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    title:
      "【アイドル熱唱】「高嶺のなでしこ」VS「PeeltheApple」カラオケ本気バトル！モーニング娘。・キャンディーズ・超ときめき宣伝部…今旬アイドルが伝説アイドル曲を歌い上げる！《アイドル神声バトル》",
    authorName: "動画、はじめてみました【テレビ朝日公式】",
    publishedAt: "2023-08-07",
    mediaUrl: "https://youtu.be/AefOHYVIuHo",
    imageUrl: "https://i.ytimg.com/vi/AefOHYVIuHo/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "高嶺のなでしこ、「初恋のひと。」と1周年単独ライブを紹介するインタビュー実施！..「9月3日1周年単独ライブたくさん来てくださいね~」",
    authorName: "wowKorea FAN",
    publishedAt: "2023-07-19",
    mediaUrl: "https://youtu.be/_tU8lAPv684",
    imageUrl: "https://i.ytimg.com/vi/_tU8lAPv684/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title:
      "高嶺のなでしこ、「全国お招きツアー2023~First trip~」ツアーファイナル初単独公演インタビュー実施… 「ぜひ見に来てくださいますよね？」",
    authorName: "wowKorea FAN",
    publishedAt: "2023-06-14",
    mediaUrl: "https://youtu.be/NQBiKzJY4gE",
    imageUrl: "https://i.ytimg.com/vi/NQBiKzJY4gE/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title: "“高嶺のなでしこ”が夏休みの合宿免許をPR★ご予約は運転免許トロッカ！",
    authorName: "運転免許トロッカ!",
    publishedAt: "2023-05-19",
    mediaUrl: "https://youtu.be/bwjBjaTIlBk",
    imageUrl: "https://i.ytimg.com/vi/bwjBjaTIlBk/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    title: "運転免許トロッカ！新アンバサダー“高嶺のなでしこ”メッセージ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2023-04-17",
    mediaUrl: "https://youtu.be/35lxvC668Ek",
    imageUrl: "https://i.ytimg.com/vi/35lxvC668Ek/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    title: "高嶺のなでしこ VANITYMIX WEB LIMITED INTERVIEW",
    authorName: "VANITYMIX マガジン",
    publishedAt: "2023-04-04",
    mediaUrl: "https://www.vanitymix.jp/music/takanenonadeshiko/",
    imageUrl: "https://www.vanitymix.jp/wp-content/uploads/2023/04/takane-Aph-fix.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    title: "#26 学生フォーミュラ日本大会2022を振り返って（リポーターたちの対談）",
    authorName: "(公社)自動車技術会",
    publishedAt: "2023-01-18",
    mediaUrl: "https://youtu.be/3tFd2i9UdFA",
    imageUrl: "https://i.ytimg.com/vi/3tFd2i9UdFA/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり", "松本ももな"],
  },
];
