export interface ShopBenefits {
  shopName: string;
  merchandises: {
    name: string;
    price: number;
    edition: "スペシャル盤" | "初回限定盤" | "たかねこ盤" | "たかねこセット";
    sku?: string;
    bonuses: string[];
    reservationStart: string;
    reservationEnd?: string;
    url: string;
  }[];
}

export const ECSites: ShopBenefits[] = [
  {
    shopName: "ビクターオンラインストア",
    merchandises: [
      {
        name: "【早期予約特典付】見上げるたびに、恋をする。 | スペシャル盤 | CD+BOOK",
        price: 11000,
        edition: "スペシャル盤",
        sku: "VIZL-2481",
        bonuses: [
          "メンバー直筆サイン入り着せ替えジャケット（ランダム9種） 4 枚",
          "オリジナルポストカード〈絵柄C〉",
        ],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104371",
      },
      {
        name: "【早期予約特典付】見上げるたびに、恋をする。 | 初回限定盤 | CD+DVD",
        price: 5500,
        edition: "初回限定盤",
        sku: "VIZL-2482",
        bonuses: [
          "メンバー直筆サイン入り着せ替えジャケット（ランダム9種） 2 枚",
          "オリジナルポストカード〈絵柄C〉",
        ],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104370",
      },
      {
        name: "【早期予約特典付】見上げるたびに、恋をする。 | たかねこ盤 | CD",
        price: 3300,
        edition: "たかねこ盤",
        sku: "VICL-66101",
        bonuses: [
          "メンバー直筆サイン入り着せ替えジャケット（ランダム9種） 1 枚",
          "オリジナルポストカード〈絵柄C〉",
        ],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104369",
      },
      {
        name: "【城月菜央 サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14694",
        bonuses: ["サイン入りアクリルフレーム（城月菜央）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-25",
        url: "https://victor-store.jp/item/104388",
      },
      {
        name: "【涼海すう サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14695",
        bonuses: ["サイン入りアクリルフレーム（涼海すう）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-25",
        url: "https://victor-store.jp/item/104387",
      },
      {
        name: "【橋本桃呼 サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14696",
        bonuses: ["サイン入りアクリルフレーム（橋本桃呼）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104386",
      },
      {
        name: "【葉月紗蘭 サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14697",
        bonuses: ["サイン入りアクリルフレーム（葉月紗蘭）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104385",
      },
      {
        name: "【東山恵里沙 サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14698",
        bonuses: ["サイン入りアクリルフレーム（東山恵里沙）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104384",
      },
      {
        name: "【日向端ひな サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14699",
        bonuses: ["サイン入りアクリルフレーム（日向端ひな）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104383",
      },
      {
        name: "【星谷美来 サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14700",
        bonuses: ["サイン入りアクリルフレーム（星谷美来）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104382",
      },
      {
        name: "【松本ももな サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14701",
        bonuses: ["サイン入りアクリルフレーム（松本ももな）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104381",
      },
      {
        name: "【籾山ひめり サイン入り】見上げるたびに、恋をする。| たかねこセット | スペシャル盤＋初回限定盤＋たかねこ盤＋サイン入りアクリルフレーム",
        price: 23300,
        edition: "たかねこセット",
        sku: "VOSF-14702",
        bonuses: ["サイン入りアクリルフレーム（籾山ひめり）", "オリジナルポストカード〈絵柄C〉"],
        reservationStart: "2025-09-07",
        reservationEnd: "2025-09-15",
        url: "https://victor-store.jp/item/104380",
      },
    ],
  },
  {
    shopName: "楽天ブックス",
    merchandises: [
      {
        name: "【楽天ブックス限定先着特典】見上げるたびに、恋をする。 (スペシャル盤 CD＋BOOK)(アクリルスタンド (メンバーランダム9種))",
        price: 11000,
        edition: "スペシャル盤",
        sku: " VIZL-2481",
        bonuses: ["アクリルスタンド (メンバーランダム9種)"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://books.rakuten.co.jp/rb/18369630/",
      },
      {
        name: "【楽天ブックス限定先着特典】見上げるたびに、恋をする。 (初回限定盤 CD＋DVD)(アクリルスタンド (メンバーランダム9種))",
        price: 5500,
        edition: "初回限定盤",
        sku: " VIZL-2482",
        bonuses: ["アクリルスタンド (メンバーランダム9種)"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://books.rakuten.co.jp/rb/18369632/",
      },
      {
        name: "【楽天ブックス限定先着特典】見上げるたびに、恋をする。 (たかねこ盤)(アクリルスタンド (メンバーランダム9種))",
        price: 3300,
        edition: "たかねこ盤",
        sku: "VICL-66101",
        bonuses: ["アクリルスタンド (メンバーランダム9種)"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://books.rakuten.co.jp/rb/18369631/",
      },
      {
        name: "見上げるたびに、恋をする。 (初回限定盤 CD＋DVD)",
        price: 5500,
        edition: "初回限定盤",
        sku: "VIZL-2482",
        bonuses: [],
        reservationStart: "",
        reservationEnd: "",
        url: "https://books.rakuten.co.jp/rb/18369629",
      },
    ],
  },
  {
    shopName: "セブンネットショッピング",
    merchandises: [
      {
        name: "高嶺のなでしこ／見上げるたびに、恋をする。（スペシャル盤／CD+BOOK）（セブンネット限定特典：アクリルコースター（メンバーランダム９種））",
        price: 11000,
        edition: "スペシャル盤",
        sku: "VIZL-2481",
        bonuses: ["アクリルコースター（メンバーランダム９種）"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://7net.omni7.jp/detail/1301583085",
      },
      {
        name: "高嶺のなでしこ／見上げるたびに、恋をする。（初回限定盤／CD+DVD）（セブンネット限定特典：アクリルコースター（メンバーランダム９種）） ",
        price: 5500,
        edition: "初回限定盤",
        sku: "VIZL-2482",
        bonuses: ["アクリルコースター（メンバーランダム９種）"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://7net.omni7.jp/detail/1301583086",
      },
      {
        name: "高嶺のなでしこ／見上げるたびに、恋をする。（たかねこ盤／CD）（セブンネット限定特典：アクリルコースター（メンバーランダム９種））",
        price: 3300,
        edition: "たかねこ盤",
        sku: "VICL-66101",
        bonuses: ["アクリルコースター（メンバーランダム９種）"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://7net.omni7.jp/detail/1301583087",
      },
      {
        name: "高嶺のなでしこ／見上げるたびに、恋をする。（スペシャル盤+初回限定盤+たかねこ盤　3枚セット）（セブンネット限定特典：アクリルコースター（メンバーランダム９種）×3）",
        price: 19800,
        edition: "たかねこ盤",
        bonuses: ["アクリルコースター（メンバーランダム９種）×3"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://7net.omni7.jp/detail/1301583088",
      },
    ],
  },
  {
    shopName: "Amazon.co.jp",
    merchandises: [
      {
        name: "【Amazon.co.jp限定】見上げるたびに、恋をする。 [スペシャル盤] [CD ＋ BOOK] - 高嶺のなでしこ （Amazon.co.jp限定特典 ： メガジャケ　付）",
        price: 11000,
        edition: "スペシャル盤",
        sku: "VIZL-2481",
        bonuses: ["メガジャケ"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://amzn.asia/d/fcwvCjk",
      },
      {
        name: "【Amazon.co.jp限定】見上げるたびに、恋をする。 [初回限定盤] [CD ＋ DVD] - 高嶺のなでしこ （Amazon.co.jp限定特典 ： メガジャケ　付）",
        price: 5500,
        edition: "初回限定盤",
        sku: "VIZL-2482",
        bonuses: ["メガジャケ"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://amzn.asia/d/6zz1zVy",
      },
      {
        name: "【Amazon.co.jp限定】見上げるたびに、恋をする。 [通常盤] [CD] - 高嶺のなでしこ （Amazon.co.jp限定特典 ： メガジャケ　付）",
        price: 3300,
        edition: "たかねこ盤",
        sku: "VICL-66101",
        bonuses: ["メガジャケ"],
        reservationStart: "",
        reservationEnd: "",
        url: "https://amzn.asia/d/2ZTsGFC",
      },
      {
        name: "見上げるたびに、恋をする。 [スペシャル盤] [CD ＋ BOOK] - 高嶺のなでしこ",
        price: 11000,
        edition: "スペシャル盤",
        sku: "VIZL-2481",
        bonuses: [],
        reservationStart: "",
        reservationEnd: "",
        url: "https://amzn.asia/d/02YX8IH",
      },
      {
        name: "見上げるたびに、恋をする。 [初回限定盤] [CD ＋ DVD] - 高嶺のなでしこ",
        price: 5500,
        edition: "初回限定盤",
        sku: "VIZL-2482",
        bonuses: [],
        reservationStart: "",
        reservationEnd: "",
        url: "https://amzn.asia/d/eBJ50SZ",
      },
      {
        name: "見上げるたびに、恋をする。 [通常盤] [CD] - 高嶺のなでしこ",
        price: 3300,
        edition: "たかねこ盤",
        sku: "VICL-66101",
        bonuses: [],
        reservationStart: "",
        reservationEnd: "",
        url: "https://amzn.asia/d/hhDwTXz",
      },
    ],
  },
  {
    shopName: "タワーレコード",
    merchandises: [],
  },
  {
    shopName: "HMV&BOOKS online",
    merchandises: [],
  },
];

/*
{
  name: "",
  price: ,
  edition: "",
  sku: "",
  bonuses: [
    "",
    "",
  ],
  reservationStart: "",
  reservationEnd: "",
  url: "",
},
*/
