import { MediaDetails } from "~/features/media/types";

export const metadata2026: MediaDetails[] = [
  {
    kind: "youtube",
    key: "VZmluxfUZ-w",
    title: "エピローグ〜再会　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-27",
    mediaUrl: "https://youtu.be/VZmluxfUZ-w",
    imageUrl: "https://i.ytimg.com/vi/VZmluxfUZ-w/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "-ntodupoL-8",
    title: "「上を向いて歩こう」〜記録を撮り重ねて〜　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-27",
    mediaUrl: "https://youtu.be/-ntodupoL-8",
    imageUrl: "https://i.ytimg.com/vi/-ntodupoL-8/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "pgcgmmoiwfo",
    title: "「Arrietty’s Song」〜トンネルの向こう〜　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-23",
    mediaUrl: "https://youtu.be/pgcgmmoiwfo",
    imageUrl: "https://i.ytimg.com/vi/pgcgmmoiwfo/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "096zDixTAdQ",
    title: "「テルーの唄」〜原始の森のように〜　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-23",
    mediaUrl: "https://youtu.be/096zDixTAdQ",
    imageUrl: "https://i.ytimg.com/vi/096zDixTAdQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "ogp",
    key: "https://natalie.mu/music/pp/churaku-takaneko03",
    title:
      "高嶺のなでしこ×「牛乳を飲んで、酪農応援！プレゼントキャンペーン」｜笑顔で伝える牛乳の普遍的な“おいしさ” - 音楽ナタリー 特集・インタビュー",
    authorName: "音楽ナタリー",
    publishedAt: "2026-02-20",
    mediaUrl: "https://natalie.mu/music/pp/churaku-takaneko03",
    imageUrl:
      "https://ogre.natalie.mu/media/pp/churaku-takaneko03/churaku-takaneko03_x-4.jpg?imwidth=1280&imdensity=1",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "tBGwtoXIet8",
    title: "「世界の約束」〜新しい旅に出よう〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-19",
    mediaUrl: "https://youtu.be/tBGwtoXIet8",
    imageUrl: "https://i.ytimg.com/vi/tBGwtoXIet8/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "39fi5RWX8lA",
    title: "「朝ごはんの歌」〜春の予感〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-19",
    mediaUrl: "https://youtu.be/39fi5RWX8lA",
    imageUrl: "https://i.ytimg.com/vi/39fi5RWX8lA/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "93ujrV0JClQ",
    title: "「さよならの夏」〜夏祭りにそよぐ風〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-13",
    mediaUrl: "https://youtu.be/93ujrV0JClQ",
    imageUrl: "https://i.ytimg.com/vi/93ujrV0JClQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "5K67ZivleSc",
    title: "「地球儀」〜そして未来へと歩み出す〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-13",
    mediaUrl: "https://youtu.be/5K67ZivleSc",
    imageUrl: "https://i.ytimg.com/vi/5K67ZivleSc/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "wzvyHl7Y15g",
    title: "「いつも何度でも」〜消えゆく風を抱きしめる〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-09",
    mediaUrl: "https://youtu.be/wzvyHl7Y15g",
    imageUrl: "https://i.ytimg.com/vi/wzvyHl7Y15g/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "WKrTTyIsk1k",
    title: "「カントリー・ロード」〜夢と知りせば〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-09",
    mediaUrl: "https://youtu.be/WKrTTyIsk1k",
    imageUrl: "https://i.ytimg.com/vi/WKrTTyIsk1k/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "QEtZ5r3i9Qo",
    title: "「はにゅうの宿」〜過ぎ去りし日々〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-04",
    mediaUrl: "https://youtu.be/QEtZ5r3i9Qo",
    imageUrl: "https://i.ytimg.com/vi/QEtZ5r3i9Qo/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "aNIMMC5gM7M",
    title:
      "「やさしさに包まれたなら」〜明日の日は確かならず〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-04",
    mediaUrl: "https://youtu.be/aNIMMC5gM7M",
    imageUrl: "https://i.ytimg.com/vi/aNIMMC5gM7M/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/780056",
    title: "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第8回『呪詛』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2026-01-29",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/780056",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2026/01/777508_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "Ip9nyLB1m-I",
    title: "「風になる」〜彼女は追いつけない風〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-01-28",
    mediaUrl: "https://youtu.be/Ip9nyLB1m-I",
    imageUrl: "https://i.ytimg.com/vi/Ip9nyLB1m-I/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "HTZuILRv7lQ",
    title: "「ひこうき雲」〜空を駆ける〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-01-28",
    mediaUrl: "https://youtu.be/HTZuILRv7lQ",
    imageUrl: "https://i.ytimg.com/vi/HTZuILRv7lQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "qF7TrecoG3I",
    title: "「プロローグ〜想い出」 ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-01-26",
    mediaUrl: "https://youtu.be/qF7TrecoG3I",
    imageUrl: "https://i.ytimg.com/vi/qF7TrecoG3I/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "ogp",
    key: "https://beeeem.com/article/takaneko-beeeem2",
    title: "高嶺のなでしこ 松本ももな × 籾山ひめり、立ち止まり、考え、前へ進んだ1年-BEEEEM",
    authorName: "BEEEEM",
    publishedAt: "2026-01-25",
    mediaUrl: "https://beeeem.com/article/takaneko-beeeem2",
    imageUrl:
      "https://imagedelivery.net/GAZ6B7nYxar6-1ZqFjo_3w/445674c9-6283-4d2d-1a52-473c8cc73600/medium",
    category: "article",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://kansai.pia.co.jp/interview/music/2026-01/takanenonadeshiko.html",
    title:
      "ファーストアルバムに刻まれた“9人それぞれの強み”。高嶺のなでしこ インタビュー - インタビュー＆レポート | ぴあ関西版WEB",
    authorName: "関西ぴあ",
    publishedAt: "2026-01-13",
    mediaUrl: "https://kansai.pia.co.jp/interview/music/2026-01/takanenonadeshiko.html",
    imageUrl: "/media/2026/2026-01-13_関西ぴあ.jpg",
    category: "article",
    presents: ["涼海すう", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/80796/",
    title: "お正月太りをリセット♡年始からの痩せ美容習慣",
    authorName: "Popteen Media",
    publishedAt: "2026-01-05",
    mediaUrl: "https://popteen.co.jp/media/80796/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/12/c0dfe507dc2b4d597e13da5ee369c2c6.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
];
