import { MediaDetails } from "~/features/media/types";

export const metadata2026: MediaDetails[] = [
  {
    kind: "youtube",
    key: "kRs6P8ALYFM",
    title: "個性爆発！「高嶺のなでしこ」の悩みとは【音楽マシマシ 2025.7.28OA】",
    authorName: "音楽マシマシ",
    publishedAt: "2026-05-08",
    mediaUrl: "https://youtu.be/kRs6P8ALYFM",
    imageUrl: "https://i.ytimg.com/vi/kRs6P8ALYFM/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/787967",
    title:
      "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第11回『The Dolls with Attitude』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2026-04-30",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/787967",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2026/04/787967_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "duH-dQ7PV9Y",
    title:
      "【オーディション#2】涙の最終審査、その結末は…？専属モデルに選ばれるのは誰だ！？【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2026-04-25",
    mediaUrl: "https://youtu.be/duH-dQ7PV9Y",
    imageUrl: "https://i.ytimg.com/vi/duH-dQ7PV9Y/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/85625/",
    title:
      "専属モデルオーディション2026ファイナルバトル！UP-Tプレゼンツ「おしゃTプロデュースバトル」START♡",
    authorName: "Popteen Media",
    publishedAt: "2026-04-24",
    mediaUrl: "https://popteen.co.jp/media/85625/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2026/04/14f33b0838b42bd08cc16d57105b180f-1024x1024.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "l-TqNx3c6DI",
    title:
      "【城月菜央】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-23",
    mediaUrl: "https://youtu.be/l-TqNx3c6DI",
    imageUrl: "https://i.ytimg.com/vi/l-TqNx3c6DI/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "JodRjFhlbpg",
    title:
      "【涼海すう】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-22",
    mediaUrl: "https://youtu.be/JodRjFhlbpg",
    imageUrl: "https://i.ytimg.com/vi/JodRjFhlbpg/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "youtube",
    key: "WqKSws79oAM",
    title:
      "【橋本桃呼】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-21",
    mediaUrl: "https://youtu.be/WqKSws79oAM",
    imageUrl: "https://i.ytimg.com/vi/WqKSws79oAM/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "jNDtrY7Dv6k",
    title:
      "【神回】ゆぴえなが豪華ゲストに突撃！YouTuber、アイドル、アーティスト…夢のコラボが実現しました！！！",
    authorName: "ゆうぴーまん",
    publishedAt: "2026-04-20",
    mediaUrl: "https://youtu.be/jNDtrY7Dv6k",
    imageUrl: "https://i.ytimg.com/vi/jNDtrY7Dv6k/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "qEWp2StFybI",
    title:
      "【葉月紗蘭】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-20",
    mediaUrl: "https://youtu.be/qEWp2StFybI",
    imageUrl: "https://i.ytimg.com/vi/qEWp2StFybI/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "ogp",
    key: "https://www.entax.news/post/202604201900.html",
    title:
      "『高嶺のなでしこ』メンバー全員が共感した“アイドルならではの事情”とは「○○がすごく必要になった」“十代のうちにやりたいこと”【独自インタビュー】|entax（エンタックス）",
    authorName: "entax（エンタックス）",
    publishedAt: "2026-04-20",
    mediaUrl: "https://www.entax.news/post/202604201900.html",
    imageUrl: "https://www.entax.news/wp-content/uploads/2026/04/20260414-6Y2A6106_3_re0420top.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "MePVvltgZH0",
    title:
      "【東山恵里沙】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-17",
    mediaUrl: "https://youtu.be/MePVvltgZH0",
    imageUrl: "https://i.ytimg.com/vi/MePVvltgZH0/hqdefault.jpg",
    category: "youtube",
    presents: ["東山恵里沙"],
  },
  {
    kind: "youtube",
    key: "PZlJ3hLqAKo",
    title:
      "【日向端ひな】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-16",
    mediaUrl: "https://youtu.be/PZlJ3hLqAKo",
    imageUrl: "https://i.ytimg.com/vi/PZlJ3hLqAKo/hqdefault.jpg",
    category: "youtube",
    presents: ["日向端ひな"],
  },
  {
    kind: "youtube",
    key: "jiL7iOfQde8",
    title:
      "【星谷美来】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-15",
    mediaUrl: "https://youtu.be/jiL7iOfQde8",
    imageUrl: "https://i.ytimg.com/vi/jiL7iOfQde8/hqdefault.jpg",
    category: "youtube",
    presents: ["星谷美来"],
  },
  {
    kind: "youtube",
    key: "pj-Peo9qKlU",
    title:
      "【松本ももな】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-14",
    mediaUrl: "https://youtu.be/pj-Peo9qKlU",
    imageUrl: "https://i.ytimg.com/vi/pj-Peo9qKlU/hqdefault.jpg",
    category: "youtube",
    presents: ["松本ももな"],
  },
  {
    kind: "youtube",
    key: "gpdiWijfFXg",
    title:
      "【籾山ひめり】たかねこが合宿免許を10秒PR！～夏休みver～｜運転免許トロッカ！×高嶺のなでしこ",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-14",
    mediaUrl: "https://youtu.be/gpdiWijfFXg",
    imageUrl: "https://i.ytimg.com/vi/gpdiWijfFXg/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "t1rcMa7xMYo",
    title:
      "【安藤楓×城月菜央コラボ配信】Road to 6.25Kanadevia Hall 特別企画「Devil ANTHEM. 4月個人配信」",
    authorName: "Devil ANTHEM.",
    publishedAt: "2026-04-14",
    mediaUrl: "https://youtu.be/t1rcMa7xMYo",
    imageUrl: "https://i.ytimg.com/vi/t1rcMa7xMYo/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "5EbcSIIbhFU",
    title:
      "【高嶺のなでしこ】夏休みの合宿免許は！｜城月菜央・葉月紗蘭・星谷美来【運転免許トロッカ！】",
    authorName: "運転免許トロッカ!",
    publishedAt: "2026-04-14",
    mediaUrl: "https://youtu.be/5EbcSIIbhFU",
    imageUrl: "https://i.ytimg.com/vi/5EbcSIIbhFU/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "葉月紗蘭", "星谷美来"],
  },
  {
    kind: "ogp",
    key: "https://menkyo-torocca.jp/feature/takanenonadeshiko4.html",
    title: "運転免許トロッカ！×高嶺のなでしこ｜合宿免許なら運転免許トロッカ！ ",
    authorName: "運転免許トロッカ！",
    publishedAt: "2026-04-13",
    mediaUrl: "https://menkyo-torocca.jp/feature/takanenonadeshiko4.html",
    imageUrl: "https://menkyo-torocca.jp/images/common/torocca_ogp_takaneko.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "4fGyJySBBg4",
    title:
      "【オーディション#1】Popteen専属モデルオーディション開催！ファイナリストに選ばれるのは？【Popteen】",
    authorName: "PopteenTV",
    publishedAt: "2026-04-04",
    mediaUrl: "https://youtu.be/4fGyJySBBg4",
    imageUrl: "https://i.ytimg.com/vi/4fGyJySBBg4/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/84943/",
    title: "専属モデルオーディション2026♡ファイナリストプロフィール&審査内容を一挙公開！",
    authorName: "Popteen Media",
    publishedAt: "2026-04-01",
    mediaUrl: "https://popteen.co.jp/media/84943/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2026/03/311d2167324271b9b46813799d7411fb-1024x1024.png",
    category: "article",
    presents: ["涼海すう"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/784581",
    title:
      "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第10回『WEAPONS／ウェポンズ』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2026-04-01",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/784581",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2026/03/784581_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "ogp",
    key: "https://beeeem.com/article/irc2026-takaneko",
    title:
      "【＜CREATEs presents IRC 2026＞インタビュー】高嶺のなでしこ「世界観にしっかり入り込めるように、クールな雰囲気を意識して頑張りました」-BEEEEM",
    authorName: "BEEEEM",
    publishedAt: "2026-03-23",
    mediaUrl: "https://beeeem.com/article/irc2026-takaneko",
    imageUrl:
      "https://imagedelivery.net/GAZ6B7nYxar6-1ZqFjo_3w/29057d6d-ee95-497e-9a24-efc103bde000/medium",
    category: "article",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://www.music-culture.info/8589/",
    title:
      "松本ももな（高嶺のなでしこ）木野稟子（α＋）小熊まむ（iLiFE!）佐藤綺星・小栗有以（AKB48）『CREATEs presents IRC 2026』『ゼンレスゾーンゼロ』に登場するアイドル陣営『妄想エンジェル』のキャラクターをイメージした衣装に身を包みランウェイに登場",
    authorName: "Music Culture：ミュージックカルチャー",
    publishedAt: "2026-03-19",
    mediaUrl: "https://www.music-culture.info/8589/",
    imageUrl:
      "https://image.jimcdn.com/app/cms/image/transf/none/path/s719b6af472505b2d/image/ia7ef53ffd2f66beb/version/1773913214/image.jpg",
    category: "article",
    presents: ["松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://actresspress.com/idolrunwaycollection20260315/",
    title:
      "松本ももな、籾山ひめり、阿部菜々実、橋本桃呼、大森莉緒らMC村重杏奈と共演『IDOL RUNWAY COLLECTION 2026』（写真26枚）【Reporter：熊谷美咲】 | ACTRESS PRESS",
    authorName: "ACTRESS PRESS",
    publishedAt: "2026-03-19",
    mediaUrl: "https://actresspress.com/idolrunwaycollection20260315/",
    imageUrl:
      "https://actresspress.com/wp-content/uploads/2026/03/1-thumb-idolrunwaycollection-actresspress20260315.jpg",
    category: "article",
    presents: ["橋本桃呼", "松本ももな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "TaYEbfdZcqk",
    title: "高嶺のなでしこ「美しく生きろ」など３曲熱唱　CREATEs presents IRC 2026",
    authorName: "vois ヴォイス",
    publishedAt: "2026-03-16",
    mediaUrl: "https://youtu.be/TaYEbfdZcqk",
    imageUrl: "https://i.ytimg.com/vi/TaYEbfdZcqk/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://mikan-incomplete.com/report/142339",
    title: "高嶺のなでしこが力強いパフォーマンスで圧倒！【IDOL RUNWAY COLLECTION 2026】 | 蜜柑通信",
    authorName: "蜜柑通信",
    publishedAt: "2026-03-16",
    mediaUrl: "https://mikan-incomplete.com/report/142339",
    imageUrl: "https://mikan-incomplete.com/wp-content/uploads/2026/03/JPG748.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://mdpr.jp/news/4747179",
    title:
      "“元ラストアイドル”高嶺のなでしこ・橋本桃呼＆フルコース阿部菜々実がランウェイ競演 カラージャケットのイロチコーデ【IDOL RUNWAY COLLECTION 2026】 - モデルプレス",
    authorName: "モデルプレス - ライフスタイル・ファッションエンタメニュース",
    publishedAt: "2026-03-16",
    mediaUrl: "https://mdpr.jp/news/4747179",
    imageUrl:
      "https://img-mdpr.freetls.fastly.net/article/B1nU/wm/B1nUfzx7ulPqWjxalXLAPSsbKLa9yzy1hA2PZwWbV3k.jpg",
    category: "article",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "RVMjUw4nAzs",
    title:
      "元ラスアイ・阿部菜々実＆橋本桃呼がペアでランウェイ　AKB48平田侑希はフルコースの中川心と",
    authorName: "vois ヴォイス",
    publishedAt: "2026-03-15",
    mediaUrl: "https://youtu.be/RVMjUw4nAzs",
    imageUrl: "https://i.ytimg.com/vi/RVMjUw4nAzs/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼"],
  },
  {
    kind: "youtube",
    key: "gFn9dOcBJjY",
    title: "５時に夢中！スピンオフ特番 『ミルクにモ～夢中！』 2026　クッキングシーン映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2026-03-06",
    mediaUrl: "https://youtu.be/gFn9dOcBJjY",
    imageUrl: "https://i.ytimg.com/vi/gFn9dOcBJjY/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "w2yuxRhPPxQ",
    title: "５時に夢中！スピンオフ特番 『ミルクにモ～夢中！』 2026　プリン　クッキングシーン映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2026-03-06",
    mediaUrl: "https://youtu.be/w2yuxRhPPxQ",
    imageUrl: "https://i.ytimg.com/vi/w2yuxRhPPxQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "youtube",
    key: "uK9GQP8dHDs",
    title:
      "５時に夢中！スピンオフ特番 『ミルクにモ～夢中！』 2026　クラムチャウダー　クッキングシーン映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2026-03-06",
    mediaUrl: "https://youtu.be/uK9GQP8dHDs",
    imageUrl: "https://i.ytimg.com/vi/uK9GQP8dHDs/hqdefault.jpg",
    category: "youtube",
    presents: ["城月菜央", "東山恵里沙", "松本ももな"],
  },
  {
    kind: "youtube",
    key: "SE71MiND2rY",
    title: "５時に夢中！スピンオフ特番 『ミルクにモ～夢中！』 2026　ドリア　クッキングシーン映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2026-03-06",
    mediaUrl: "https://youtu.be/SE71MiND2rY",
    imageUrl: "https://i.ytimg.com/vi/SE71MiND2rY/hqdefault.jpg",
    category: "youtube",
    presents: ["涼海すう", "橋本桃呼", "星谷美来"],
  },
  {
    kind: "youtube",
    key: "NKKwfXKnUS8",
    title: "高嶺のなでしこ、HEROINES FES 2026の盛り上がりを語る！",
    authorName: "WWS チャンネル",
    publishedAt: "2026-03-04",
    mediaUrl: "https://youtu.be/NKKwfXKnUS8",
    imageUrl: "https://i.ytimg.com/vi/NKKwfXKnUS8/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "youtube",
    key: "Z_ir5EhW1OA",
    title: "スタジオジブリ トリビュートアルバム「ジブリをうたう その２」ショートムービーメイキング",
    authorName: "Victor Entertainment",
    publishedAt: "2026-03-04",
    mediaUrl: "https://youtu.be/Z_ir5EhW1OA",
    imageUrl: "https://i.ytimg.com/vi/Z_ir5EhW1OA/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/781951",
    title: "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第9回『羊たちの沈黙』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2026-02-28",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/781951",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2026/02/781951_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "VZmluxfUZ-w",
    title: "エピローグ〜再会　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-27",
    mediaUrl: "https://youtu.be/VZmluxfUZ-w",
    imageUrl: "https://i.ytimg.com/vi/VZmluxfUZ-w/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "-ntodupoL-8",
    title: "「上を向いて歩こう」〜記録を撮り重ねて〜　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-27",
    mediaUrl: "https://youtu.be/-ntodupoL-8",
    imageUrl: "https://i.ytimg.com/vi/-ntodupoL-8/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "pgcgmmoiwfo",
    title: "「Arrietty’s Song」〜トンネルの向こう〜　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-23",
    mediaUrl: "https://youtu.be/pgcgmmoiwfo",
    imageUrl: "https://i.ytimg.com/vi/pgcgmmoiwfo/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "096zDixTAdQ",
    title: "「テルーの唄」〜原始の森のように〜　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-23",
    mediaUrl: "https://youtu.be/096zDixTAdQ",
    imageUrl: "https://i.ytimg.com/vi/096zDixTAdQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "sUTI8BRnoE4",
    title: "「牛乳を飲んで、酪農応援！」プレゼントキャンペーンCM映像",
    authorName: "一般社団法人中央酪農会議",
    publishedAt: "2026-02-20",
    mediaUrl: "https://youtu.be/sUTI8BRnoE4",
    imageUrl: "https://i.ytimg.com/vi/sUTI8BRnoE4/hqdefault.jpg",
    category: "youtube",
    presents: [],
  },
  {
    kind: "ogp",
    key: "https://natalie.mu/music/pp/churaku-takaneko03",
    title:
      "高嶺のなでしこ×「牛乳を飲んで、酪農応援！プレゼントキャンペーン」｜笑顔で伝える牛乳の普遍的な“おいしさ” - 音楽ナタリー 特集・インタビュー",
    authorName: "音楽ナタリー",
    publishedAt: "2026-02-20",
    mediaUrl: "https://natalie.mu/music/pp/churaku-takaneko03",
    imageUrl:
      "https://ogre.natalie.mu/media/pp/churaku-takaneko03/churaku-takaneko03_x-4.jpg?imwidth=1280&imdensity=1",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "tBGwtoXIet8",
    title: "「世界の約束」〜新しい旅に出よう〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-19",
    mediaUrl: "https://youtu.be/tBGwtoXIet8",
    imageUrl: "https://i.ytimg.com/vi/tBGwtoXIet8/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "39fi5RWX8lA",
    title: "「朝ごはんの歌」〜春の予感〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-19",
    mediaUrl: "https://youtu.be/39fi5RWX8lA",
    imageUrl: "https://i.ytimg.com/vi/39fi5RWX8lA/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "93ujrV0JClQ",
    title: "「さよならの夏」〜夏祭りにそよぐ風〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-13",
    mediaUrl: "https://youtu.be/93ujrV0JClQ",
    imageUrl: "https://i.ytimg.com/vi/93ujrV0JClQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "5K67ZivleSc",
    title: "「地球儀」〜そして未来へと歩み出す〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-13",
    mediaUrl: "https://youtu.be/5K67ZivleSc",
    imageUrl: "https://i.ytimg.com/vi/5K67ZivleSc/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "wzvyHl7Y15g",
    title: "「いつも何度でも」〜消えゆく風を抱きしめる〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-09",
    mediaUrl: "https://youtu.be/wzvyHl7Y15g",
    imageUrl: "https://i.ytimg.com/vi/wzvyHl7Y15g/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "WKrTTyIsk1k",
    title: "「カントリー・ロード」〜夢と知りせば〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-09",
    mediaUrl: "https://youtu.be/WKrTTyIsk1k",
    imageUrl: "https://i.ytimg.com/vi/WKrTTyIsk1k/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "QEtZ5r3i9Qo",
    title: "「はにゅうの宿」〜過ぎ去りし日々〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-04",
    mediaUrl: "https://youtu.be/QEtZ5r3i9Qo",
    imageUrl: "https://i.ytimg.com/vi/QEtZ5r3i9Qo/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "aNIMMC5gM7M",
    title:
      "「やさしさに包まれたなら」〜明日の日は確かならず〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-02-04",
    mediaUrl: "https://youtu.be/aNIMMC5gM7M",
    imageUrl: "https://i.ytimg.com/vi/aNIMMC5gM7M/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "ogp",
    key: "https://www.tvlife.jp/pickup/kizukinao/780056",
    title: "ホラー大好き城月菜央の「ホラー、ほら、おもろい」第8回『呪詛』 | TV LIFE web",
    authorName: "TV LIFE web",
    publishedAt: "2026-01-29",
    mediaUrl: "https://www.tvlife.jp/pickup/kizukinao/780056",
    imageUrl: "https://www.tvlife.jp/wps/wp-content/uploads/2026/01/777508_01.jpg",
    category: "article",
    presents: ["城月菜央"],
  },
  {
    kind: "youtube",
    key: "Ip9nyLB1m-I",
    title: "「風になる」〜彼女は追いつけない風〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-01-28",
    mediaUrl: "https://youtu.be/Ip9nyLB1m-I",
    imageUrl: "https://i.ytimg.com/vi/Ip9nyLB1m-I/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "HTZuILRv7lQ",
    title: "「ひこうき雲」〜空を駆ける〜 　ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-01-28",
    mediaUrl: "https://youtu.be/HTZuILRv7lQ",
    imageUrl: "https://i.ytimg.com/vi/HTZuILRv7lQ/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "youtube",
    key: "qF7TrecoG3I",
    title: "「プロローグ〜想い出」 ジブリをうたう その2　ショートムービー",
    authorName: "Victor Entertainment",
    publishedAt: "2026-01-26",
    mediaUrl: "https://youtu.be/qF7TrecoG3I",
    imageUrl: "https://i.ytimg.com/vi/qF7TrecoG3I/hqdefault.jpg",
    category: "youtube",
    presents: ["葉月紗蘭"],
  },
  {
    kind: "ogp",
    key: "https://beeeem.com/article/takaneko-beeeem2",
    title: "高嶺のなでしこ 松本ももな × 籾山ひめり、立ち止まり、考え、前へ進んだ1年-BEEEEM",
    authorName: "BEEEEM",
    publishedAt: "2026-01-25",
    mediaUrl: "https://beeeem.com/article/takaneko-beeeem2",
    imageUrl:
      "https://imagedelivery.net/GAZ6B7nYxar6-1ZqFjo_3w/445674c9-6283-4d2d-1a52-473c8cc73600/medium",
    category: "article",
    presents: ["松本ももな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://kansai.pia.co.jp/interview/music/2026-01/takanenonadeshiko.html",
    title:
      "ファーストアルバムに刻まれた“9人それぞれの強み”。高嶺のなでしこ インタビュー - インタビュー＆レポート | ぴあ関西版WEB",
    authorName: "関西ぴあ",
    publishedAt: "2026-01-13",
    mediaUrl: "https://kansai.pia.co.jp/interview/music/2026-01/takanenonadeshiko.html",
    imageUrl: "/media/2026/2026-01-13_関西ぴあ.jpg",
    category: "article",
    presents: ["涼海すう", "日向端ひな", "籾山ひめり"],
  },
  {
    kind: "ogp",
    key: "https://popteen.co.jp/media/80796/",
    title: "お正月太りをリセット♡年始からの痩せ美容習慣",
    authorName: "Popteen Media",
    publishedAt: "2026-01-05",
    mediaUrl: "https://popteen.co.jp/media/80796/",
    imageUrl:
      "https://popteen.co.jp/media/wp-content/uploads/sites/2/2025/12/c0dfe507dc2b4d597e13da5ee369c2c6.jpg",
    category: "article",
    presents: ["涼海すう"],
  },
];
