import { ItemDescription } from "./product";

export const REGULAR_PHOTO_SET = [
  { id: 1, name: "城月菜央", description: "ヨリ" },
  { id: 2, name: "城月菜央", description: "チュウ" },
  { id: 3, name: "城月菜央", description: "ヒキ" },
  { id: 4, name: "涼海すう", description: "ヨリ" },
  { id: 5, name: "涼海すう", description: "チュウ" },
  { id: 6, name: "涼海すう", description: "ヒキ" },
  { id: 7, name: "橋本桃呼", description: "ヨリ" },
  { id: 8, name: "橋本桃呼", description: "チュウ" },
  { id: 9, name: "橋本桃呼", description: "ヒキ" },
  { id: 10, name: "葉月紗蘭", description: "ヨリ" },
  { id: 11, name: "葉月紗蘭", description: "チュウ" },
  { id: 12, name: "葉月紗蘭", description: "ヒキ" },
  { id: 13, name: "春野莉々", description: "ヨリ" },
  { id: 14, name: "春野莉々", description: "チュウ" },
  { id: 15, name: "春野莉々", description: "ヒキ" },
  { id: 16, name: "東山恵里沙", description: "ヨリ" },
  { id: 17, name: "東山恵里沙", description: "チュウ" },
  { id: 18, name: "東山恵里沙", description: "ヒキ" },
  { id: 19, name: "日向端ひな", description: "ヨリ" },
  { id: 20, name: "日向端ひな", description: "チュウ" },
  { id: 21, name: "日向端ひな", description: "ヒキ" },
  { id: 22, name: "星谷美来", description: "ヨリ" },
  { id: 23, name: "星谷美来", description: "チュウ" },
  { id: 24, name: "星谷美来", description: "ヒキ" },
  { id: 25, name: "松本ももな", description: "ヨリ" },
  { id: 26, name: "松本ももな", description: "チュウ" },
  { id: 27, name: "松本ももな", description: "ヒキ" },
  { id: 28, name: "籾山ひめり", description: "ヨリ" },
  { id: 29, name: "籾山ひめり", description: "チュウ" },
  { id: 30, name: "籾山ひめり", description: "ヒキ" },
];

export const REGULAR_MINI_PHOTO_SET = [
  { id: 1, name: "城月菜央", description: "" },
  { id: 2, name: "城月菜央", description: "" },
  { id: 3, name: "城月菜央", description: "" },
  { id: 4, name: "涼海すう", description: "" },
  { id: 5, name: "涼海すう", description: "" },
  { id: 6, name: "涼海すう", description: "" },
  { id: 7, name: "橋本桃呼", description: "" },
  { id: 8, name: "橋本桃呼", description: "" },
  { id: 9, name: "橋本桃呼", description: "" },
  { id: 10, name: "葉月紗蘭", description: "" },
  { id: 11, name: "葉月紗蘭", description: "" },
  { id: 12, name: "葉月紗蘭", description: "" },
  { id: 13, name: "春野莉々", description: "" },
  { id: 14, name: "春野莉々", description: "" },
  { id: 15, name: "春野莉々", description: "" },
  { id: 16, name: "東山恵里沙", description: "" },
  { id: 17, name: "東山恵里沙", description: "" },
  { id: 18, name: "東山恵里沙", description: "" },
  { id: 19, name: "日向端ひな", description: "" },
  { id: 20, name: "日向端ひな", description: "" },
  { id: 21, name: "日向端ひな", description: "" },
  { id: 22, name: "星谷美来", description: "" },
  { id: 23, name: "星谷美来", description: "" },
  { id: 24, name: "星谷美来", description: "" },
  { id: 25, name: "松本ももな", description: "" },
  { id: 26, name: "松本ももな", description: "" },
  { id: 27, name: "松本ももな", description: "" },
  { id: 28, name: "籾山ひめり", description: "" },
  { id: 29, name: "籾山ひめり", description: "" },
  { id: 30, name: "籾山ひめり", description: "" },
];

const ALL_LINEUP_CHARACTERS = [
  "城月菜央",
  "涼海すう",
  "橋本桃呼",
  "葉月紗蘭",
  "春野莉々",
  "東山恵里沙",
  "日向端ひな",
  "星谷美来",
  "松本ももな",
  "籾山ひめり",
  "てんにゃ",
  "ルニャ・コーチ",
  "すうにゃろう",
  "はしもと もふ呼",
  "らあら",
  "ルノリスくん",
  "にゃーさ",
  "たま",
  "ちゃーみー",
  "ぽにゃん🎀",
  "もみさん。",
];

export const flattenLineup = (lineup: ItemDescription[]): string[] => {
  return ALL_LINEUP_CHARACTERS.filter((character) =>
    lineup.some((item) => item.name === character),
  );
};
