import { MediaDetails } from "~/features/media/types";

export const metadata2022: MediaDetails[] = [
  {
    kind: "ogp",
    key: "https://ticket.rakuten.co.jp/features/interview221229/",
    title: "アイドル情報専門ページ【R-IDOL】 | インタビュー｜高嶺のなでしこ",
    authorName: "アイドル情報専門ページ【R-IDOL】",
    publishedAt: "2022-12-29",
    mediaUrl: "https://ticket.rakuten.co.jp/features/interview221229/",
    imageUrl:
      "https://ticketscmspro.blob.core.windows.net/%24web/usersite/uploaded/RT/676469/676470/asset/images/interview/001.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "d3uN2mkIovE",
    title: "#22【本大会まとめ⑩】学生フォーミュラ日本大会：リポーターが伝える会場の様子",
    authorName: "(公社)自動車技術会",
    publishedAt: "2022-12-27",
    mediaUrl: "https://youtu.be/d3uN2mkIovE",
    imageUrl: "https://i.ytimg.com/vi/d3uN2mkIovE/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり", "松本ももな"],
  },
  {
    kind: "ogp",
    key: "https://cmnow.jp/entertainment/22102914413/",
    title: "いま話題の「たかねこ」ちゃんとは!? 1stファンミーティング直前まとめ – CMNOW WEB",
    authorName: "CMNOW WEB",
    publishedAt: "2022-10-31",
    mediaUrl: "https://cmnow.jp/entertainment/22102914413/",
    imageUrl: "https://cmnow.jp/wp-content/uploads/2022/10/M7_0253-1600x1600.jpg",
    category: "article",
    presents: [],
  },
  {
    kind: "youtube",
    key: "Jqjk6IZE3qk",
    title: "#11【2022年大会参戦チームのリアル】東京農工大学③_学生フォーミュラ日本大会",
    authorName: "(公社)自動車技術会",
    publishedAt: "2022-10-06",
    mediaUrl: "https://youtu.be/Jqjk6IZE3qk",
    imageUrl: "https://i.ytimg.com/vi/Jqjk6IZE3qk/hqdefault.jpg",
    category: "youtube",
    presents: ["橋本桃呼", "松本ももな"],
  },
  {
    kind: "youtube",
    key: "lu0x7gQKNSQ",
    title: "#10【2022年大会参戦チームのリアル】豊橋技術科学大学②_学生フォーミュラ日本大会",
    authorName: "(公社)自動車技術会",
    publishedAt: "2022-09-29",
    mediaUrl: "https://youtu.be/lu0x7gQKNSQ",
    imageUrl: "https://i.ytimg.com/vi/lu0x7gQKNSQ/hqdefault.jpg",
    category: "youtube",
    presents: ["籾山ひめり"],
  },
];
